/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-09-03 18:59:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.index.Logado;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Tela_005fde_005fLogado_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

  String nome = request.getParameter("nome_User");
  String email = request.getParameter("email_User");
  String senha = request.getParameter("senha_User");
  int id = Integer.parseInt(request.getParameter("id_User"));
  
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"pt-br\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Clíca Santos</title>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"CSS-logado.css\">\r\n");
      out.write("    <script src=\"script.js\"></script>\r\n");
      out.write("  </head>\r\n");
      out.write("  <style>\r\n");
      out.write("    .txt {\r\n");
      out.write("    border-collapse: collapse;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    background-color: #fff;\r\n");
      out.write("    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* Sombra suave */\r\n");
      out.write("    }\r\n");
      out.write("    th, td {\r\n");
      out.write("    border: 1px solid #ccc;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    padding: 12px; /* Maior espaço interno */\r\n");
      out.write("    }\r\n");
      out.write("    th {\r\n");
      out.write("    background-color: #f2f2f2;\r\n");
      out.write("    }\r\n");
      out.write("    tr:hover {\r\n");
      out.write("    background-color: #bcb8b8; /* Cor de fundo quando hover (passar o mouse) */\r\n");
      out.write("    }\r\n");
      out.write("    .hoje {\r\n");
      out.write("    background-color: #1E90FF;\r\n");
      out.write("    color:#fff;\r\n");
      out.write("    }\r\n");
      out.write("    .conteiner-titulo-0{\r\n");
      out.write("    margin-top: 15%;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    justify-items: center;\r\n");
      out.write("    padding: 25px;\r\n");
      out.write("    }\r\n");
      out.write("    .container-calendario{\r\n");
      out.write("    background-color: #fff; \r\n");
      out.write("    }\r\n");
      out.write("    .container-calendario .icon-seta{\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("    .container-calendario.icon-seta:hover{\r\n");
      out.write("    background-color: #1E90FF;\r\n");
      out.write("    }\r\n");
      out.write("    #mesExibido{\r\n");
      out.write("    font-size: 30px;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <header>\r\n");
      out.write("      <nav class=\"nav-menu\">\r\n");
      out.write("        <div class=\"hamburger-menu\" onclick=\"toggleMenu()\">\r\n");
      out.write("          <span class=\"material-icons  controla\">reorder</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <ul class=\"menu-list\">\r\n");
      out.write("          <li><a class=\"nav-menu-a\" href=\"#\">Agenda</a></li>\r\n");
      out.write("          <li><a class=\"nav-menu-a\" href=\"#\">Calendário</a></li>\r\n");
      out.write("          <li><a class=\"nav-menu-a\" href=\"#\">Serviços</a></li>\r\n");
      out.write("          <li><a class=\"nav-menu-a\" href=\"#\" class=\"dropbtn\" onclick=\"redirecionarParaAnimais()\">Animais</a></li>\r\n");
      out.write("          <li class=\"dropdown\">\r\n");
      out.write("            <button class=\"btnLogin-popup\">Login</button>\r\n");
      out.write("            <div class=\"dropdown-content\">\r\n");
      out.write("              <span class=\"a-dropdown\" onclick=\"openModalEntrar()\">Alterar</span>\r\n");
      out.write("              <span class=\"a-dropdown\" onclick=\"openModalCadastrar()\">Deletar </span>                  \r\n");
      out.write("            </div>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("    <div class=\"logo\">\r\n");
      out.write("      <img class=\"logo\" src=\"imgs/Logo_Clínica-removebg-preview.png\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <section>\r\n");
      out.write("      <img class=\"img3\" src=\"imgs/castracao-de-caes-e-gatos.jpg\" alt=\"Img3\">\r\n");
      out.write("      <div class=\"conteiner-titulo-0\">\r\n");
      out.write("        <div class=\"texto\">\r\n");
      out.write("          <h1 class=\"txt-agenda\">Seja bem-vindo senhor ");
      out.print(nome );
      out.write(" </h1>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"container-calendario\">\r\n");
      out.write("          <span onclick=\"mesAnterior()\"><span class=\"material-symbols-outlined  icon-seta\">arrow_back</span></span>\r\n");
      out.write("          <span id=\"mesExibido\" ></span>\r\n");
      out.write("          <span onclick=\"proximoMes()\"><span class=\"material-symbols-outlined icon-seta\">arrow_forward</span></span>\r\n");
      out.write("          <p id=\"calendario\" class=\"txt\" ></p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <div id=\"entrar\" class=\"modal\">\r\n");
      out.write("      <!-- modal alterar -->\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <span class=\"close\" onclick=\"closeModal_entrar()\">&times;</span>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <h1>Alterar</h1>\r\n");
      out.write("          <h2>Tem certeza que deseja alterar?</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("        <form action=\"../../User/Alterar.jsp\" method=\"post\">\r\n");
      out.write("          <p>Código de usuário</p>\r\n");
      out.write("          <input type=\"text\" name=\"idcliente\" id=\"idcliente\" disabled=\"disabled\" value=\"");
      out.print(id);
      out.write("\">\r\n");
      out.write("          <input type=\"hidden\" name=\"huser\" id=\"huser\" value=\"");
      out.print(id);
      out.write("\">\r\n");
      out.write("          <p>Nome:</p>\r\n");
      out.write("          <input type=\"text\" name=\"nome\" id=\"nome\" value=\"");
      out.print(nome);
      out.write("\">\r\n");
      out.write("          <p>E-mail:</p>\r\n");
      out.write("          <input type=\"email\" name=\"email\" id=\"email\" value=\"");
      out.print(email);
      out.write("\" required>\r\n");
      out.write("          <input type=\"hidden\" name=\"email_antigo\" id=\"email_antigo\" value=\"");
      out.print(email);
      out.write("\" >\r\n");
      out.write("          <p>Senha:</p>\r\n");
      out.write("          <input type=\"password\" name=\"senha_entrar\" id=\"senha_entrar\" value=\"");
      out.print(senha);
      out.write("\" required><!-- visibilidade de senha entrar -->\r\n");
      out.write("          <label id=\"mostrar_senha_entrar\" class=\"box-modal\" onclick=\"exibirSenhaEntrar()\">🔒</label>\r\n");
      out.write("          <button type=\"submit\" class=\"button-modal\">Alterar</button>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"cadastrar\" class=\"modal\">\r\n");
      out.write("      <!-- modal deletar -->\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <span class=\"close\" onclick=\"closeModal_cadastrar()\">&times;</span>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <h1>Cadastre-se</h1>\r\n");
      out.write("          <h2>Curando patinhas e corações: nossa clínica veterinária é o lar do cuidado e amor.</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("        <form action=\"../../User/Deletar.jsp\" method=\"post\">\r\n");
      out.write("          <input type=\"text\" name=\"idcliente\" id=\"idcliente\" disabled=\"disabled\" value=\"");
      out.print( id );
      out.write("\">\r\n");
      out.write("          <input type=\"hidden\" name=\"huser\" id=\"huser\" value=\"");
      out.print( id );
      out.write("\">\r\n");
      out.write("          <p>Nome:</p>\r\n");
      out.write("          <input type=\"text\" name=\"nome\" id=\"nome\" disabled=\"disabled\" value=\"");
      out.print( nome);
      out.write("\">\r\n");
      out.write("          <p>E-mail:</p>\r\n");
      out.write("          <input type=\"email\" name=\"email\" id=\"email\" disabled=\"disabled\" value=\"");
      out.print( email);
      out.write("\" required>\r\n");
      out.write("          <p>Senha:</p>\r\n");
      out.write("          <input type=\"password\" name=\"senha_cadastrar\" id=\"senha_cadastrar\" disabled=\"disabled\" Value=\"");
      out.print(senha);
      out.write("\" required> <!-- visibilidade de senha cadastrar -->\r\n");
      out.write("          <label id=\"mostrar_senha_cadastrar\" class=\"box-modal\" onclick=\"exibirSenhaCadastro()\">🔒</label>\r\n");
      out.write("          <button type=\"submit\" class=\"button-modal\">Deletar</button>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- segunda parte do site. corpo após o tituloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo -->\r\n");
      out.write("    <header class=\"segunda-parte\">\r\n");
      out.write("      <div class=\"container-titulo-1\">\r\n");
      out.write("        <div>\r\n");
      out.write("          <h1 id=\"h1-segunda-parte\">Cirurgiões Veterinários para cães e gatos em Belém do Pará</h1>\r\n");
      out.write("          <p id=\"p-segunda-parte\">O centro cirúrgico da Clínica Santos possui os materiais e equipamentos necessários para realizar um procedimento seguro e com a mais alta qualidade, além de que contamos com uma médica veterinária especializada em cirurgia de tecidos moles.\r\n");
      out.write("            <br><br>\r\n");
      out.write("            As indicações de cirurgias são variadas, no entanto, as mais realizadas são as castrações seguidas da mastectomia e das cirurgias oculares e abdominais.\r\n");
      out.write("          </p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <img id=\"imagem-titulo-1\" src=\"imgs/img1.jpg\" alt=\"imagem-de-cachorro\">\r\n");
      out.write("      </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!-- terceira parte do siteeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee -->\r\n");
      out.write("    <article>\r\n");
      out.write("      <div class=\"container-titulo-2\">\r\n");
      out.write("        <h1 id=\"titulo-segunda-parte\">Serviços Veterinarios</h1>\r\n");
      out.write("        <div class=\"container-box\">\r\n");
      out.write("          <div class=\"box\">\r\n");
      out.write("            <img class=\"imagem-box\" src=\"imgs/icon-Cirurgias.png\" alt=\"immagem-de-fisio\">\r\n");
      out.write("            <p>Fisioterapia veterinária</p>\r\n");
      out.write("            <br>\r\n");
      out.write("            <p>Cirurgias de segurança com uma equipe especializada. Cirurgias veterinárias em Belém.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"box\">\r\n");
      out.write("            <img class=\"imagem-box\" src=\"imgs/icon-fisio.png\" alt=\"immagem-de-fisio\">\r\n");
      out.write("            <p>Fisioterapia veterinária</p>\r\n");
      out.write("            <br>\r\n");
      out.write("            <p>Fisioterapia para animais de todos os portes. Fisioterapia animal em Belém.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"box\">\r\n");
      out.write("            <img class=\"imagem-box\" src=\"imgs/icon-exame.png\" alt=\"immagem-de-exame\">\r\n");
      out.write("            <p>Exames</p>\r\n");
      out.write("            <br>\r\n");
      out.write("            <p>Exames de sangue e exames laboratoriais. Exames médicos em Belém.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"box\">\r\n");
      out.write("            <img class=\"imagem-box\" src=\"imgs/icon-consulta.png\" alt=\"immagem-de-fisio\">\r\n");
      out.write("            <p>Consultas</p>\r\n");
      out.write("            <br>\r\n");
      out.write("            <p>Agende sua consulta com um médico especializado. Consultas médicas em Belém.</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br>\r\n");
      out.write("        <div id=\"end-da-terceira-parte\">\r\n");
      out.write("          <p id=\"p-terceira-parte\">Nossa clínica veterinária oferece serviços de qualidade com preços acessíveis. Consultas e exames em diversas especialidades. Conheça a nossa clínica em Belém.</p>\r\n");
      out.write("          <button id=\"button-segunda-parte\">Sobre a Clínica</button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </article>\r\n");
      out.write("    <!-- fooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooter -->\r\n");
      out.write("    <footer>\r\n");
      out.write("      <div class=\"footer-content\">\r\n");
      out.write("        <div class=\"footer-logo\">\r\n");
      out.write("          <img  class=\"img-logo\" src=\"imgs/Logo_Clínica-removebg-preview.png\" alt=\"Logo da Clínica\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"footer-links\">\r\n");
      out.write("          <ul class=\"footer-menu\">\r\n");
      out.write("            <li><a href=\"#\">Termos de Uso</a></li>\r\n");
      out.write("            <li><a href=\"#\">Política de Privacidade</a></li>\r\n");
      out.write("            <li><a href=\"#\">Mapa do Site</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"footer-contact\">\r\n");
      out.write("          <p>Entre em contato:</p>\r\n");
      out.write("          <p>Telefone: (91) 94002-8922</p>\r\n");
      out.write("          <p>Email: contato@clinicasantos.com</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"social-icons\">\r\n");
      out.write("          <a href=\"#\" class=\"icon\"><i class=\"fab fa-facebook\"></i></a>\r\n");
      out.write("          <a href=\"#\" class=\"icon\"><i class=\"fab fa-twitter\"></i></a>\r\n");
      out.write("          <a href=\"#\" class=\"icon\"><i class=\"fab fa-instagram\"></i></a>\r\n");
      out.write("          <a href=\"#\" class=\"icon\"><i class=\"fab fa-linkedin\"></i></a>\r\n");
      out.write("          <a href=\"#\" class=\"icon\"><i class=\"fab fa-youtube\"></i></a>\r\n");
      out.write("          <a href=\"#\" class=\"icon\"><i class=\"fab fa-github\"></i></a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"footer-bottom\">\r\n");
      out.write("        <p>&copy; 2023 Clínica Santos. Todos os direitos reservados.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <form id=\"return_Form\" action=\"../../Animal_User/Pagina_animal.jsp\" method=\"post\">\r\n");
      out.write("      <input type=\"hidden\" name=\"id_User\" id=\"id_User\" value=\"");
      out.print(id);
      out.write("\" />    \r\n");
      out.write("      \r\n");
      out.write("    </form>\r\n");
      out.write("    <script>\r\n");
      out.write("      exibirCalendario();\r\n");
      out.write("      \r\n");
      out.write("      function redirecionarParaAnimais() {\r\n");
      out.write("      	 document.getElementById(\"return_Form\").submit();\r\n");
      out.write("      }\r\n");
      out.write("    </script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
