/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-10-03 12:15:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ADM;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import DAO.AnimalClienteDAO;
import DTO.Animal_UserDTO;
import DAO.UserDAO;
import DTO.UserDTO;
import java.util.ArrayList;

public final class ADM_005fLista_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("DTO.UserDTO");
    _jspx_imports_classes.add("DAO.AnimalClienteDAO");
    _jspx_imports_classes.add("DAO.UserDAO");
    _jspx_imports_classes.add("DTO.Animal_UserDTO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0\" />\r\n");
      out.write("\r\n");
      out.write(" <link rel=\"stylesheet\" href=\"wasds.css\">\r\n");
      out.write("<title>Tela de Listar Cliente</title>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<main class=\"container\">\r\n");
      out.write("  <h1>Lista de <b>animais</b></h1>\r\n");
      out.write("  \r\n");
      out.write("  <div id=\"pesq-div\">\r\n");
      out.write("    <input type=\"text\" id=\"pesq-caixa\" placeholder=\"Digite o nome do dono\">\r\n");
      out.write("    <button id=\"pesq-button\">Pesquisar</button>\r\n");
      out.write("    <button id=\"desfazer-button\">Desfazer</button> <!-- Botão de Desfazer -->\r\n");
      out.write("  </div>\r\n");
      out.write("  <div id=\"filtro-div\">\r\n");
      out.write("    <input type=\"radio\" id=\"filtro-dono\" name=\"filtro\" value=\"dono\" checked>\r\n");
      out.write("    <label for=\"filtro-dono\">Pesquisar por Dono</label>\r\n");
      out.write("    <input type=\"radio\" id=\"filtro-animal\" name=\"filtro\" value=\"animal\">\r\n");
      out.write("    <label for=\"filtro-animal\">Pesquisar por Animal</label>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write(" ");

UserDAO userDAO = new UserDAO();
ArrayList<UserDTO> users = userDAO.ArrayListarUser();

AnimalClienteDAO animal = new AnimalClienteDAO();
ArrayList<Animal_UserDTO> dono = animal.ListarAnimaisClientes();
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      <table>\r\n");
      out.write("      <tr>\r\n");
      out.write("        <th>ID dono</th>\r\n");
      out.write("        <th>Dono</th>\r\n");
      out.write("        <th>Nome animal</th> \r\n");
      out.write("        <th>Especie</th> \r\n");
      out.write("        <th>Raça</th>\r\n");
      out.write("        <th>Dt nascimento</th> \r\n");
      out.write("        <th>ID animal</th> \r\n");
      out.write("        <th>Alterar</th>\r\n");
      out.write("        <th>Deletar</th>\r\n");
      out.write("        \r\n");
      out.write("      </tr>\r\n");
      out.write("      ");
 
    
      for (UserDTO user_dono : users) {
    	 int idDesejado = user_dono.getId_user();
      
      for (Animal_UserDTO user : dono) {
    	   if (user.getCliente().getId_user() == idDesejado) { 
    		   
    		   
      
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      <tr>\r\n");
      out.write("        <td>");
      out.print(user_dono.getId_user() );
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print( user_dono.getNome());
      out.write("</td>  \r\n");
      out.write("        <td>");
      out.print( user.getNome_animal() );
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print( user.getEspecie() );
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print( user.getRaca());
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print( user.getData_nascimento());
      out.write("</td>\r\n");
      out.write("        <td>");
      out.print( user.getId_animal());
      out.write("</td> \r\n");
      out.write("        <td> <button class=\"button-deleta\" onclick=\"preencherFormularioAlterar('");
      out.print( user.getId_animal() );
      out.write("', '");
      out.print( user.getNome_animal() );
      out.write("', '");
      out.print( user.getEspecie() );
      out.write("', '");
      out.print( user.getRaca() );
      out.write("', '");
      out.print( user.getData_nascimento());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(user_dono.getId_user() );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print( user_dono.getNome() );
      out.write("')\"><span class=\"material-symbols-outlined\">edit</span></button></td>\r\n");
      out.write("        <td> <button class=\"button-deleta\" onclick=\"preencherFormularioDeletar('");
      out.print( user.getId_animal() );
      out.write("', '");
      out.print( user.getNome_animal() );
      out.write("', '");
      out.print( user.getEspecie() );
      out.write("', '");
      out.print( user.getRaca() );
      out.write("', '");
      out.print( user.getData_nascimento());
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print( user_dono.getNome() );
      out.write("')\"><span class=\"material-symbols-outlined\">Delete</span></button></td>\r\n");
      out.write("        \r\n");
      out.write("      </tr>\r\n");
      out.write("      ");
 
    	  }
       }
      }
      
      out.write("\r\n");
      out.write("     \r\n");
      out.write("    </table>\r\n");
      out.write("    <table>    \r\n");
      out.write("    <tr>\r\n");
      out.write("    <td><div id=\"resultado-nao-encontrado\" style=\"display: none;\"><h1 class=\"titulo-container\">Não encontrado</h1></div></td>\r\n");
      out.write("    </tr>    \r\n");
      out.write("    </table>\r\n");
      out.write("<!-- modal alterar animal -->\r\n");
      out.write("    <div id=\"alterar\" class=\"modal\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("          <span class=\"close\" onclick=\"closeModalAlterar()\">&times;</span>\r\n");
      out.write("          <div class=\"container-modal\">\r\n");
      out.write("            <h1>Alterar</h1>\r\n");
      out.write("          </div>\r\n");
      out.write("          <form action=\"Alterar_animal.jsp\" method=\"post\"  class=\"modal-form\">\r\n");
      out.write("          <span>Dono:</span>\r\n");
      out.write("          <input type=\"text\" name=\"nome_dono_alt\" id=\"nome_dono_alt\" disabled=\"disabled\">\r\n");
      out.write("          <input type=\"hidden\" name=\"idDesejado\" id=\"idDesejado\"  value=\"\">\r\n");
      out.write("            <span>Código animal:</span>	\r\n");
      out.write("            <input type=\"text\" name=\"id_animal_altera\" id=\"id_animal_altera\" disabled=\"disabled\" value=\"\">\r\n");
      out.write("            <input type=\"hidden\" name=\"id_animal_hidden_altera\" id=\"id_animal_hidden_altera\" value=\"\">\r\n");
      out.write("            <span>Nome:</span>\r\n");
      out.write("            <input type=\"text\" name=\"nome_altera\" id=\"nome_altera\"  value=\"\">\r\n");
      out.write("            <span>Especie:</span>\r\n");
      out.write("            <select  name=\"especie_animal_altera\" id=\"especie_animal_altera\" onchange=\"carregarRacas()\" required>\r\n");
      out.write("              <option value=\"Cachorro\">Cachorro</option>\r\n");
      out.write("              <option value=\"Gato\">Gato</option>\r\n");
      out.write("              <option value=\"Pássaro\">Pássaro</option>\r\n");
      out.write("              <option value=\"Hamster\">Hamster</option>\r\n");
      out.write("              <option value=\"Coelho\">Coelho</option>\r\n");
      out.write("              <option value=\"Rato\">Rato</option>\r\n");
      out.write("              <option value=\"Peixe\">Peixe</option>\r\n");
      out.write("              <option value=\"Cavalo\">Cavalo</option>\r\n");
      out.write("              <option value=\"Papagaio\">Papagaio</option>\r\n");
      out.write("              <option value=\"Tartaruga\">Tartaruga</option>\r\n");
      out.write("              <option value=\"Galinha\">Galinha</option>\r\n");
      out.write("              <option value=\"Porco\">Porco</option>\r\n");
      out.write("              <option value=\"Serpente\">Serpente</option>\r\n");
      out.write("              <option value=\"Elefante\">Elefante</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            <span>Raça:</span>\r\n");
      out.write("            <select name=\"raca_animal_altera\" id=\"raca_animal_altera\" required>\r\n");
      out.write("              \r\n");
      out.write("            </select>\r\n");
      out.write("            <span>Data de nascimento:	</span>\r\n");
      out.write("            <input type=\"date\" name=\"data_nascimento_animal_altera\" id=\"data_nascimento_animal_altera\" Value=\"\" >\r\n");
      out.write("            <button type=\"submit\" class=\"button-modal\">Alterar</button>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("<!-- modal deletar animal-->\r\n");
      out.write("     <!-- modal exclusão de animal -->\r\n");
      out.write("<div id=\"excluir\" class=\"modal\">\r\n");
      out.write("  <div class=\"modal-content\">\r\n");
      out.write("    <span class=\"close\" onclick=\"closeModal_Deletar()\">&times;</span>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <h1>Excluir Animal</h1>\r\n");
      out.write("    </div>\r\n");
      out.write("    <form action=\"Deletar_animal.jsp\" method=\"post\" class=\"modal-form\">\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <span>Dono:</span>\r\n");
      out.write("      <input type=\"text\" name=\"dono_deleta\" id=\"dono_deleta\" disabled=\"disabled\" value=\"\">\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("      <span>Código animal:</span>\r\n");
      out.write("      <input type=\"text\" name=\"id_animal_excluir\" id=\"id_animal_excluir\" disabled=\"disabled\" value=\"\">\r\n");
      out.write("      <input type=\"hidden\" name=\"id_animal_hidden_excluir\" id=\"id_animal_hidden_excluir\" value=\"\">\r\n");
      out.write("      <span>Nome:</span>\r\n");
      out.write("      <input type=\"text\" name=\"nome_excluir\" id=\"nome_excluir\" disabled=\"disabled\" value=\"\">\r\n");
      out.write("      <span>Espécie:</span>\r\n");
      out.write("      <input type=\"text\" name=\"especie_excluir\" id=\"especie_excluir\" disabled=\"disabled\" value=\"\">\r\n");
      out.write("      <span>Raça:</span>\r\n");
      out.write("      <input type=\"text\" name=\"raca_excluir\" id=\"raca_excluir\" disabled=\"disabled\" value=\"\">\r\n");
      out.write("      <span>Data de Nascimento:</span>\r\n");
      out.write("      <input type=\"text\" name=\"data_nascimento_excluir\" id=\"data_nascimento_excluir\" disabled=\"disabled\" value=\"\">\r\n");
      out.write("      <button type=\"submit\" class=\"button-modal\">Excluir</button>\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("     \r\n");
      out.write("</main>	\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//modal deletar\r\n");
      out.write("function closeModal_Deletar() {\r\n");
      out.write("	document.getElementById(\"excluir\").style.display = \"none\";\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("//modal alterar\r\n");
      out.write("function closeModalAlterar() {\r\n");
      out.write("	document.getElementById(\"alterar\").style.display = \"none\";\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("//modal dados\r\n");
      out.write("\r\n");
      out.write("function fecharModal() {\r\n");
      out.write("	document.getElementById(\"myModal\").style.display = \"none\";\r\n");
      out.write("	}\r\n");
      out.write("//não lembro para que serve, porém serve para voltar para uma determinada página\r\n");
      out.write("function voltar() {\r\n");
      out.write("    document.getElementById(\"return_Form\").submit();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("//Preencher os campos do formulário de alterção com os valores recebidospara alterar\r\n");
      out.write("  function preencherFormularioAlterar(id_animal, nome_animal, especie, raca, data_nascimento, id_user, dono) {\r\n");
      out.write("   \r\n");
      out.write("   document.getElementById(\"id_animal_altera\").value = id_animal;\r\n");
      out.write("   document.getElementById(\"nome_altera\").value = nome_animal;\r\n");
      out.write("   document.getElementById(\"especie_animal_altera\").value = especie;\r\n");
      out.write("   document.getElementById(\"raca_animal_altera\").value = raca;\r\n");
      out.write("   document.getElementById(\"data_nascimento_animal_altera\").value = data_nascimento;\r\n");
      out.write("   document.getElementById(\"idDesejado\").value = id_user;\r\n");
      out.write("   \r\n");
      out.write("   document.getElementById(\"nome_dono_alt\").value = dono;\r\n");
      out.write("   \r\n");
      out.write("   document.getElementById(\"id_animal_hidden_altera\").value = id_animal;\r\n");
      out.write("\r\n");
      out.write("   document.getElementById(\"alterar\").style.display = \"block\";\r\n");
      out.write("   \r\n");
      out.write("   carregarRacas(raca);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//Preencher os campos do formulário de deletar com os valores recebidos para deletar \r\n");
      out.write("  function preencherFormularioDeletar(id_animal, nome_animal, especie, raca, data_nascimento,nome_dono) {\r\n");
      out.write("  document.getElementById(\"dono_deleta\").value = nome_dono;\r\n");
      out.write("  document.getElementById(\"id_animal_excluir\").value = id_animal;\r\n");
      out.write("  document.getElementById(\"nome_excluir\").value = nome_animal;\r\n");
      out.write("  document.getElementById(\"especie_excluir\").value = especie;\r\n");
      out.write("  document.getElementById(\"raca_excluir\").value = raca;\r\n");
      out.write("  document.getElementById(\"data_nascimento_excluir\").value = data_nascimento;\r\n");
      out.write("  document.getElementById(\"id_animal_hidden_excluir\").value = id_animal;\r\n");
      out.write("\r\n");
      out.write("  // Exibir o modal de exclusão\r\n");
      out.write("  document.getElementById(\"excluir\").style.display = \"block\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//valores do select de alteração\r\n");
      out.write("  function carregarRacas(valor) {\r\n");
      out.write("	  const especieSelectAltera = document.getElementById(\"especie_animal_altera\");\r\n");
      out.write("	  const racaSelectAltera = document.getElementById(\"raca_animal_altera\");\r\n");
      out.write("	  const exibe = valor;\r\n");
      out.write("	\r\n");
      out.write("	  const racasPossiveisAltera = {\r\n");
      out.write("			  \"Cachorro\": [\"Vira lata \",\"Pastor Alemão\", \"Golden Retriever\", \"Labrador\", \"Bulldog\", \"Poodle\", \"Boxer\", \"Husky\", \"Dálmata\", \"Bulldog Francês\", \"Chihuahua\"],\r\n");
      out.write("		        \"Gato\": [\"Siamese\", \"Persa\", \"Bengal\", \"Maine Coon\", \"Sphynx\", \"Ragdoll\", \"British Shorthair\", \"Scottish Fold\", \"Siberian\", \"Devon Rex\"],\r\n");
      out.write("		        \"Pássaro\": [\"Cacatua\", \"Canário\", \"Periquito\", \"Calopsita\", \"Papagaio\", \"Agapornis\", \"Arara\", \"Tucano\", \"Pardal\", \"Ave-do-paraíso\"],\r\n");
      out.write("		        \"Hamster\": [\"Sírio\", \"Russo\", \"Roborovski\", \"Chinês\", \"Campbell\", \"Angorá\", \"Manchuriano\", \"Mongol\", \"Siberiano\", \"Djungarian\"],\r\n");
      out.write("		        \"Coelho\": [\"Holland Lop\", \"Mini Rex\", \"Holandês\", \"Lebre Belga\", \"Fuzzy Lop\", \"Mini Lionhead\", \"Angorá\", \"Chinchila\", \"Mini Satin\", \"Californiano\"],\r\n");
      out.write("		        \"Rato\": [\"Rato de Estimação\", \"Rato Selvagem\", \"Rato de Laboratório\", \"Rato Dumbo\", \"Rato Siamese\", \"Rato Hooded\", \"Rato Albino\", \"Rato de Cauda Longa\", \"Rato Fawn\", \"Rato de Cauda Curta\"],\r\n");
      out.write("		        \"Peixe\": [\"Betta\", \"Guppy\", \"Tetra Neón\", \"Platy\", \"Peixe-espada\", \"Danio Zebra\", \"Peixe-palhaço\", \"Corydora\", \"Bala Shark\", \"Molinésia\"],\r\n");
      out.write("		        \"Cavalo\": [\"Cavalo Árabe\", \"Puro-Sangue Inglês\", \"Quarto de Milha\", \"Cavalo Appaloosa\", \"Cavalo Pônei\", \"Cavalo Shire\", \"Cavalo Frísio\", \"Cavalo Tennessee Walker\", \"Cavalo Andaluz\", \"Cavalo Haflinger\"],\r\n");
      out.write("		        \"Papagaio\": [\"Papagaio-do-congo\", \"Papagaio-cinzento\", \"Papagaio-de-cabeça-amarela\", \"Papagaio-de-cabeça-vermelha\", \"Papagaio-amazônico\", \"Papagaio-eclectus\", \"Papagaio-rosa\", \"Papagaio-molucano\", \"Papagaio-de-crista\", \"Papagaio-araçari\"],\r\n");
      out.write("		        \"Tartaruga\": [\"Tartaruga-de-ouro\", \"Tartaruga-de-ouvido-vermelho\", \"Tartaruga-pintada\", \"Tartaruga-sulcata\", \"Tartaruga-leopardo\", \"Tartaruga-mordedora-comum\", \"Tartaruga-aligátor\", \"Tartaruga-mapa\", \"Tartaruga-de-caixa\", \"Tartaruga-africana-de-carapaça-macia\"],\r\n");
      out.write("		        \"Galinha\": [\"Galinha-doméstica\", \"Galinha-seda\", \"Galinha-sussex\", \"Galinha-plymouth-rock\", \"Galinha-americana\", \"Galinha-araucana\", \"Galinha-brahma\", \"Galinha-orpington\", \"Galinha-wyandotte\", \"Galinha-leghorn\"],\r\n");
      out.write("		        \"Porco\": [\"Porco-doméstico\", \"Porco-da-índia\", \"Porco-de-miniporco\", \"Porco-da-índia\", \"Porco-da-índia-skinny\", \"Porco-do-vietnã\", \"Porco-holandês\", \"Porco-kunekune\", \"Porco-mangalica\", \"Porco-peludo\"],\r\n");
      out.write("		        \"Serpente\": [\"Serpente-de-milho\", \"Serpente-rei-da-califórnia\", \"Serpente-das-árvores\", \"Serpente-de-leite\", \"Serpente-de-milho\", \"Serpente-de-ratão\", \"Serpente-das-nuvens\", \"Serpente-boieira\", \"Serpente-rato-do-deserto\", \"Serpente-king-cobra\"],\r\n");
      out.write("		        \"Elefante\": [\"Elefante-africano\", \"Elefante-asiático\", \"Elefante-da-floresta\", \"Elefante-da-savana\", \"Elefante-africano-das-florestas\", \"Elefante-indiano\", \"Elefante-africano-de-savanas\", \"Elefante-da-floresta-africana\", \"Elefante-pigmeu\", \"Elefante-do-sri-lanka\"]\r\n");
      out.write("	  };\r\n");
      out.write("	  \r\n");
      out.write("	  const especieSelecionadaAltera = especieSelectAltera.value;\r\n");
      out.write("	  const racasAltera = racasPossiveisAltera[especieSelecionadaAltera] || [];\r\n");
      out.write("	  \r\n");
      out.write("	  racaSelectAltera.innerHTML = \"\";  \r\n");
      out.write("	  \r\n");
      out.write("	  const optionPadrao = document.createElement(\"option\");\r\n");
      out.write("	  optionPadrao.value = valor;\r\n");
      out.write("	  if(valor !=null){\r\n");
      out.write("		  optionPadrao.textContent = valor;\r\n");
      out.write("		  \r\n");
      out.write("	  }\r\n");
      out.write("	  else{\r\n");
      out.write("		  optionPadrao.textContent = \"Escolha\";\r\n");
      out.write("	  }\r\n");
      out.write("	  \r\n");
      out.write("	  racaSelectAltera.appendChild(optionPadrao);\r\n");
      out.write("	  \r\n");
      out.write("	  racasAltera.forEach((raca) => {\r\n");
      out.write("	    const option = document.createElement(\"option\");\r\n");
      out.write("	    option.value = raca;\r\n");
      out.write("	    option.textContent = raca;\r\n");
      out.write("	    racaSelectAltera.appendChild(option);\r\n");
      out.write("	  });\r\n");
      out.write("	    \r\n");
      out.write("	  \r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("	  const inputPesquisa = document.getElementById(\"pesq-caixa\");\r\n");
      out.write("	  const pesquisarButton = document.getElementById(\"pesq-button\");\r\n");
      out.write("	  const desfazerButton = document.getElementById(\"desfazer-button\");\r\n");
      out.write("	  const tabela = document.querySelector(\"table\");\r\n");
      out.write("	  const linhas = tabela.getElementsByTagName(\"tr\");\r\n");
      out.write("	  const filtroDono = document.getElementById(\"filtro-dono\");\r\n");
      out.write("	  const filtroAnimal = document.getElementById(\"filtro-animal\");\r\n");
      out.write("	  const resultadoNaoEncontrado = document.getElementById(\"resultado-nao-encontrado\");\r\n");
      out.write("\r\n");
      out.write("	  // Função para reverter a pesquisa\r\n");
      out.write("	  function desfazerPesquisa() {\r\n");
      out.write("	    inputPesquisa.value = \"\";\r\n");
      out.write("	    for (let i = 1; i < linhas.length; i++) {\r\n");
      out.write("	      linhas[i].style.display = \"\";\r\n");
      out.write("	    }\r\n");
      out.write("	    resultadoNaoEncontrado.style.display = \"none\";\r\n");
      out.write("	  }\r\n");
      out.write("\r\n");
      out.write("	  pesquisarButton.addEventListener(\"click\", function () {\r\n");
      out.write("	    const termoPesquisa = inputPesquisa.value.toLowerCase(); // Converter o termo de pesquisa em minúsculas\r\n");
      out.write("	    const filtroSelecionado = filtroDono.checked ? \"dono\" : \"animal\";\r\n");
      out.write("	    let resultadosEncontrados = 0;\r\n");
      out.write("\r\n");
      out.write("	    for (let i = 1; i < linhas.length; i++) {\r\n");
      out.write("	      const donoCelula = linhas[i].getElementsByTagName(\"td\")[1];\r\n");
      out.write("	      const animalNomeCelula = linhas[i].getElementsByTagName(\"td\")[2];\r\n");
      out.write("\r\n");
      out.write("	      if (filtroSelecionado === \"dono\" && donoCelula) {\r\n");
      out.write("	        const donoTexto = donoCelula.textContent.toLowerCase(); // Converter o texto da célula em minúsculas\r\n");
      out.write("	        if (donoTexto.includes(termoPesquisa)) {\r\n");
      out.write("	          linhas[i].style.display = \"\";\r\n");
      out.write("	          resultadosEncontrados++;\r\n");
      out.write("	        } else {\r\n");
      out.write("	          linhas[i].style.display = \"none\";\r\n");
      out.write("	        }\r\n");
      out.write("	      } else if (filtroSelecionado === \"animal\" && animalNomeCelula) {\r\n");
      out.write("	        const animalNomeTexto = animalNomeCelula.textContent.toLowerCase(); // Converter o texto da célula em minúsculas\r\n");
      out.write("	        if (animalNomeTexto.includes(termoPesquisa)) {\r\n");
      out.write("	          linhas[i].style.display = \"\";\r\n");
      out.write("	          resultadosEncontrados++;\r\n");
      out.write("	        } else {\r\n");
      out.write("	          linhas[i].style.display = \"none\";\r\n");
      out.write("	        }\r\n");
      out.write("	      }\r\n");
      out.write("	    }\r\n");
      out.write("\r\n");
      out.write("	    if (resultadosEncontrados === 0) {\r\n");
      out.write("	      resultadoNaoEncontrado.style.display = \"block\";\r\n");
      out.write("	    } else {\r\n");
      out.write("	      resultadoNaoEncontrado.style.display = \"none\";\r\n");
      out.write("	    }\r\n");
      out.write("	  });\r\n");
      out.write("\r\n");
      out.write("	  desfazerButton.addEventListener(\"click\", function () {\r\n");
      out.write("	    desfazerPesquisa();\r\n");
      out.write("	  });\r\n");
      out.write("\r\n");
      out.write("	  filtroDono.addEventListener(\"change\", function () {\r\n");
      out.write("	    pesquisarButton.click();\r\n");
      out.write("	  });\r\n");
      out.write("\r\n");
      out.write("	  filtroAnimal.addEventListener(\"change\", function () {\r\n");
      out.write("	    pesquisarButton.click();\r\n");
      out.write("	  });\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("var retorna = new URLSearchParams(window.location.search);\r\n");
      out.write("var elemento = retorna.get('conf');\r\n");
      out.write("\r\n");
      out.write("switch (elemento) {\r\n");
      out.write("case 'deletado':\r\n");
      out.write("setTimeout(function() {\r\n");
      out.write("alert('Animal deletado!');\r\n");
      out.write("}, 100);\r\n");
      out.write("break;\r\n");
      out.write("\r\n");
      out.write("case 'alterado':\r\n");
      out.write("setTimeout(function() {\r\n");
      out.write("alert('Animal alterado!');\r\n");
      out.write("}, 100);\r\n");
      out.write("break;\r\n");
      out.write("\r\n");
      out.write("case 'erro_cadastra_animal':\r\n");
      out.write("setTimeout(function() {\r\n");
      out.write("alert('O animal não pode ser cadastrado por algum motivo por parte do servidor!');\r\n");
      out.write("}, 100);\r\n");
      out.write("break;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
