/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-08-29 11:18:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.index;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import DAO.UserDAO;
import java.util.ArrayList;
import DTO.UserDTO;

public final class logado_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("DTO.UserDTO");
    _jspx_imports_classes.add("DAO.UserDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("@import url('https://fonts.googleapis.com/css2?family=Boogaloo&display=swap');\r\n");
      out.write("@import url('https://fonts.googleapis.com/css2?family=Boogaloo&family=Inter:wght@300&display=swap');\r\n");
      out.write("/* Estilo Geral */\r\n");
      out.write("*{\r\n");
      out.write("margin:0;\r\n");
      out.write("padding:0;\r\n");
      out.write("box-sizing:border-box;\r\n");
      out.write("}\r\n");
      out.write("body{\r\n");
      out.write("background-image: url(Imagens/img4.jpg);\r\n");
      out.write("background-repeat: no-repeat;\r\n");
      out.write("background-size: cover;\r\n");
      out.write("}\r\n");
      out.write("nav{\r\n");
      out.write("margin-top:20px;\r\n");
      out.write("display:flex;\r\n");
      out.write("justify-content:center;\r\n");
      out.write("}\r\n");
      out.write(".dropdown-menu{\r\n");
      out.write("display:flex;\r\n");
      out.write("flex-wrap: wrap;\r\n");
      out.write("top: 15px;\r\n");
      out.write("left: 600px;\r\n");
      out.write("width: 100%;\r\n");
      out.write("position: fixed;\r\n");
      out.write("gap:20px;\r\n");
      out.write("font-family:Inter;\r\n");
      out.write("}\r\n");
      out.write(".dropdown-menu li{\r\n");
      out.write("width:150px;\r\n");
      out.write("height:50px;\r\n");
      out.write("list-style:none;\r\n");
      out.write("}\r\n");
      out.write(".dropdown-menu a{\r\n");
      out.write("display:block;\r\n");
      out.write("width:100%;\r\n");
      out.write("height:100%;\r\n");
      out.write("color:white;\r\n");
      out.write("text-decoration:none;\r\n");
      out.write("display:flex;\r\n");
      out.write("justify-content:center;\r\n");
      out.write("align-items:center;\r\n");
      out.write("font-size:1.3rem;\r\n");
      out.write("}\r\n");
      out.write(".dropdown-menu li:hover >a{\r\n");
      out.write(" background-color: #1E90FF;\r\n");
      out.write(" COLOR:black;\r\n");
      out.write("}\r\n");
      out.write(".dropdown-menu li:hover > .dropdown-submenu{\r\n");
      out.write("display:block;\r\n");
      out.write("}\r\n");
      out.write(".dropdown-submenu{\r\n");
      out.write(" margin-top:1px;\r\n");
      out.write(" display:none;\r\n");
      out.write("}\r\n");
      out.write(".dropdown-submenu a{\r\n");
      out.write("background-color:#00000080;\r\n");
      out.write("width:150%;\r\n");
      out.write("display:flex;\r\n");
      out.write("justify-content:flex-start;\r\n");
      out.write("padding-left:20px;\r\n");
      out.write("font-size:.8rem;\r\n");
      out.write("border-left:8px solid transparent;\r\n");
      out.write("}\r\n");
      out.write(".dropdown-submenu li:hover > a{\r\n");
      out.write("border-left:8px solid black;\r\n");
      out.write("}\r\n");
      out.write(".h1p{\r\n");
      out.write("text-align:left;\r\n");
      out.write("padding:30px;\r\n");
      out.write("margin-top:0px;\r\n");
      out.write("font-family: Boogaloo;\r\n");
      out.write("font-size: 40px;\r\n");
      out.write("color:black;\r\n");
      out.write("}\r\n");
      out.write(".user{\r\n");
      out.write("text-align:left;\r\n");
      out.write("padding:30px;\r\n");
      out.write("margin-left:-720px;\r\n");
      out.write("margin-top:-290px;\r\n");
      out.write("font-family: Boogaloo;\r\n");
      out.write("font-size: 40px;\r\n");
      out.write("color:white;\r\n");
      out.write("}\r\n");
      out.write(".inf{\r\n");
      out.write("text-align:left;\r\n");
      out.write("padding:10px;\r\n");
      out.write("margin-left:-690px;\r\n");
      out.write("font-family: Inter;\r\n");
      out.write("font-size: 20px;\r\n");
      out.write("color:white;\r\n");
      out.write("}\r\n");
      out.write("h1{\r\n");
      out.write("text-align:left;\r\n");
      out.write("padding:30px;\r\n");
      out.write("margin-top:0px;\r\n");
      out.write("font-family: Boogaloo;\r\n");
      out.write("font-size: 40px;\r\n");
      out.write("color:black;\r\n");
      out.write("}\r\n");
      out.write("h2{\r\n");
      out.write("text-align:left;\r\n");
      out.write("padding:30px;\r\n");
      out.write("margin-top:40px;\r\n");
      out.write("font-family: Boogaloo;\r\n");
      out.write("font-size: 40px;\r\n");
      out.write("color:black;\r\n");
      out.write("}\r\n");
      out.write("h3{\r\n");
      out.write("text-align:center;\r\n");
      out.write("padding:30px;\r\n");
      out.write("margin-top:0px;\r\n");
      out.write("font-family: Boogaloo;\r\n");
      out.write("font-size: 40px;\r\n");
      out.write("color:white;\r\n");
      out.write("}\r\n");
      out.write(".texto2{\r\n");
      out.write("margin-top:0px;\r\n");
      out.write("padding:50px;\r\n");
      out.write("}\r\n");
      out.write(".img1{\r\n");
      out.write("max-width:50%;\r\n");
      out.write("height:auto;\r\n");
      out.write("}\r\n");
      out.write(".img3{\r\n");
      out.write("position:relative;\r\n");
      out.write("filter: brightness(40%);\r\n");
      out.write("max-width:100%;\r\n");
      out.write("height:auto;\r\n");
      out.write("display:block;\r\n");
      out.write("}\r\n");
      out.write(".text1{\r\n");
      out.write(" width: 100%;\r\n");
      out.write(" height: 500px;\r\n");
      out.write(" padding: 30px;\r\n");
      out.write(" font-family: Boogaloo;\r\n");
      out.write(" font-size:1.3rem;\r\n");
      out.write("}\r\n");
      out.write(".container{\r\n");
      out.write("overflow: hidden;\r\n");
      out.write("}\r\n");
      out.write(".img-left {\r\n");
      out.write("float: right;\r\n");
      out.write("width: 35%;\r\n");
      out.write("margin-right: 100px;\r\n");
      out.write("margin-top:-62px;\r\n");
      out.write("}\r\n");
      out.write(".container2 {\r\n");
      out.write("  display: flex;\r\n");
      out.write("  flex-wrap: wrap;\r\n");
      out.write("}\r\n");
      out.write(".container3{\r\n");
      out.write("  position: relative;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".img3 {\r\n");
      out.write("  display: block;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".texto {\r\n");
      out.write("color:white;\r\n");
      out.write("font-family: Boogaloo;\r\n");
      out.write("font-size:35px;\r\n");
      out.write("position: absolute;\r\n");
      out.write("top: 50%;\r\n");
      out.write("left: 50%;\r\n");
      out.write("transform: translate(-50%, -50%);\r\n");
      out.write("}\r\n");
      out.write(".box {\r\n");
      out.write("  background-color: white;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  font-family:Inter;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  width: calc(30% - 150px);\r\n");
      out.write("  transition: 200ms linear;\r\n");
      out.write("  height: 250px;\r\n");
      out.write("  margin: 15px;\r\n");
      out.write("}\r\n");
      out.write(".box:hover{\r\n");
      out.write("transform: scale(1.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (max-width: 768px) {\r\n");
      out.write("  .box {\r\n");
      out.write("    width: calc(100% - 10px);\r\n");
      out.write("    margin: 5px;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write(".text2{\r\n");
      out.write(" width: 100%;\r\n");
      out.write(" height: 700px;\r\n");
      out.write(" background-color: #eaeaea;\r\n");
      out.write(" padding: 20px;\r\n");
      out.write("}\r\n");
      out.write(".text3{\r\n");
      out.write(" width: 100%;\r\n");
      out.write(" height: 400px;\r\n");
      out.write(" background-image:url(Imagens/castracao-de-caes-e-gatos.jpg);\r\n");
      out.write(" background-size: cover;\r\n");
      out.write(" background-repeat: no-repeat;\r\n");
      out.write(" background-position: center center;\r\n");
      out.write(" padding: 20px;\r\n");
      out.write(" text-align:center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("section .text2{\r\n");
      out.write(" display: flex;\r\n");
      out.write(" padding:90px;\r\n");
      out.write(" background-color:#ece7e7;\r\n");
      out.write("}\r\n");
      out.write(".p1{\r\n");
      out.write(" display: block;\r\n");
      out.write(" margin-block-start: 1em;\r\n");
      out.write(" margin-block-end: 200px;\r\n");
      out.write(" margin-inline-start: 30px;\r\n");
      out.write(" margin-inline-end: 0px;\r\n");
      out.write(" text-align: justify;\r\n");
      out.write(" max-width: 800px;\r\n");
      out.write(" font-family: Inter;\r\n");
      out.write(" font-size:24px;\r\n");
      out.write("}\r\n");
      out.write(".p2{\r\n");
      out.write(" display: block;\r\n");
      out.write(" margin-block-start: 3rem;\r\n");
      out.write(" margin-inline-start: 30px;\r\n");
      out.write(" text-align: justify;\r\n");
      out.write(" max-width: 1000px;\r\n");
      out.write(" font-family: Inter;\r\n");
      out.write(" font-size:24px;\r\n");
      out.write("}\r\n");
      out.write(".p3{\r\n");
      out.write(" display: block;\r\n");
      out.write(" color:white;\r\n");
      out.write(" align-items:center;\r\n");
      out.write(" margin-block-start: 3rem;\r\n");
      out.write(" margin-left:auto;\r\n");
      out.write("margin-right:auto;\r\n");
      out.write(" text-align: justify;\r\n");
      out.write(" max-width: 1500px;\r\n");
      out.write(" font-family: Inter;\r\n");
      out.write(" font-size:24px;\r\n");
      out.write("}\r\n");
      out.write(".caixa1{\r\n");
      out.write("  width: 400px;\r\n");
      out.write("  height: 250px;\r\n");
      out.write("  border-radius: 1%;\r\n");
      out.write("  background-color: #ffffff;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  font-family:Inter;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 205%;\r\n");
      out.write("  left: 46%;\r\n");
      out.write("  transition: 200ms linear; \r\n");
      out.write("}\r\n");
      out.write(".caixa1:hover{\r\n");
      out.write(" transform: scale(1.1);\r\n");
      out.write("}\r\n");
      out.write(".caixa2{\r\n");
      out.write("  width: 400px;\r\n");
      out.write("  height: 250px;\r\n");
      out.write("  border-radius: 1%;\r\n");
      out.write("  background-color: #ffffff;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  font-family:Inter;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 175%;\r\n");
      out.write("  left: 46%;\r\n");
      out.write("  transition: 200ms linear; \r\n");
      out.write("}\r\n");
      out.write(".caixa2:hover{\r\n");
      out.write(" transform: scale(1.1);\r\n");
      out.write("}\r\n");
      out.write(".caixa3{\r\n");
      out.write("  width: 400px;\r\n");
      out.write("  height: 250px;\r\n");
      out.write("  border-radius: 1%;\r\n");
      out.write("  background-color: #ffffff;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  font-family:Inter;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 175%;\r\n");
      out.write("  left: 70%;\r\n");
      out.write("  transition: 200ms linear; \r\n");
      out.write("}\r\n");
      out.write(".caixa3:hover{\r\n");
      out.write(" transform: scale(1.1);\r\n");
      out.write("}\r\n");
      out.write(".caixa4{\r\n");
      out.write("  width: 400px;\r\n");
      out.write("  height: 250px;\r\n");
      out.write("  border-radius: 1%;\r\n");
      out.write("  background-color: #ffffff;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  font-family:Inter;\r\n");
      out.write("  padding: 10px;\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 205%;\r\n");
      out.write("  left: 70%;\r\n");
      out.write("  transition: 200ms linear; \r\n");
      out.write("}\r\n");
      out.write(".caixa4:hover{\r\n");
      out.write(" transform: scale(1.1);\r\n");
      out.write("}\r\n");
      out.write(".icons{\r\n");
      out.write("text-align: center;\r\n");
      out.write("  width: 65px;\r\n");
      out.write("  height: 65px;\r\n");
      out.write("}\r\n");
      out.write(".imagem1{\r\n");
      out.write("  display:flex;\r\n");
      out.write("}\r\n");
      out.write(".button2{\r\n");
      out.write("font-family: Boogaloo;\r\n");
      out.write("text-decoration: none;\r\n");
      out.write("padding: 10px 20px;\r\n");
      out.write("background-color: #007bff;\r\n");
      out.write("color: #ffffff;\r\n");
      out.write("display: block;\r\n");
      out.write("margin-block-start: 2.2em;\r\n");
      out.write("margin-block-end: 700px;\r\n");
      out.write("margin-inline-start: 30px;\r\n");
      out.write("margin-inline-end: 0px;\r\n");
      out.write("text-align: justify;\r\n");
      out.write("max-width: 170px;\r\n");
      out.write("font-size:25px;\r\n");
      out.write("}\r\n");
      out.write(".button3{\r\n");
      out.write("font-family: Boogaloo;\r\n");
      out.write("text-decoration: none;\r\n");
      out.write("padding: 10px 20px;\r\n");
      out.write("color: #ffffff;\r\n");
      out.write("border: 2px solid white;\r\n");
      out.write("margin-left:auto;\r\n");
      out.write("margin-right:auto;\r\n");
      out.write("display: block;\r\n");
      out.write("width:15%;\r\n");
      out.write("margin-top:60px;\r\n");
      out.write("text-align: center;\r\n");
      out.write("font-size:25px;\r\n");
      out.write("}\r\n");
      out.write(".flex{\r\n");
      out.write("display:flex;\r\n");
      out.write("}\r\n");
      out.write(".logo{\r\n");
      out.write("position:relative;\r\n");
      out.write("margin-left:-1110px;\r\n");
      out.write("margin-top:-950px;\r\n");
      out.write("}\r\n");
      out.write(".footer {\r\n");
      out.write("height: 60px; \r\n");
      out.write("background-color: #f5f5f5; \r\n");
      out.write("text-align:center;\r\n");
      out.write("padding: 20px; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Clínica Santos</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write("<div class=\"container3\">\r\n");
      out.write("<img class=\"img3\" src=\"Imagens/img3.jpg\" alt=\"Img3\">\r\n");
      out.write("<div class=\"texto\">\r\n");
      out.write("    ");

    UserDAO userDAO = new UserDAO();
    ArrayList<UserDTO> users = userDAO.ArrayListarUser();

    String email = request.getParameter("email");
    String senha = request.getParameter("senha");
    String senhaADM = null;

    boolean encontrouUsuario = false;
    String nome = "";
    int id = 0;

    for (UserDTO user : users) {
        if (user.getEmail().equals(email) && user.getSenha().equals(senha)) {
            encontrouUsuario = true;
            nome = user.getNome();
            id = user.getId_user();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<h1 class=\"user\">Bem Vindo ");
      out.print( user.getNome() );
      out.write("!</h1>\r\n");
      out.write("    \r\n");
      out.write("<p class=\"inf\">Seu ID de usuário é: ");
      out.print( user.getId_user() );
      out.write("</p>\r\n");
      out.write("<p class=\"inf\">Seu e-mail é: ");
      out.print( user.getEmail() );
      out.write("</p>\r\n");
      out.write("<p class=\"inf\">Sua senha é: ");
      out.print( user.getSenha() );
      out.write("</p>\r\n");
      out.write("\r\n");

            break;
        }
    }

      out.write("\r\n");
      out.write("\r\n");

    if (!encontrouUsuario) {

      out.write("\r\n");
      out.write("    <h1>Usuário não encontrado!</h1>\r\n");

    }

      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <nav>\r\n");
      out.write("  <img class=\"logo\" src=\"Imagens/Logo_Clínica-removebg-preview.png\" width=\"450px\" height=\"250px\">\r\n");
      out.write("    <ul class=\"dropdown-menu\">\r\n");
      out.write("        <li><a href=\"#\">A clínica</a></li>\r\n");
      out.write("        <li><a href=\"#\">Sobre nós</a></li>\r\n");
      out.write("        <li><a href=\"#\">Contatos</a></li>\r\n");
      out.write("        <li><a href=\"#\">Serviços &#9660;</a>\r\n");
      out.write("          <ul class=\"dropdown-submenu\">\r\n");
      out.write("            <li><a href=\"#\">Vacinação</a></li>\r\n");
      out.write("            <li><a href=\"#\">Castração</a></li>\r\n");
      out.write("            <li><a href=\"#\">Exames</a></li>\r\n");
      out.write("            <li><a href=\"#\">Cirurgias</a></li>\r\n");
      out.write("           </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("         <li><a href=\"#\">Conta &#9660;</a>\r\n");
      out.write("         <ul class=\"dropdown-submenu\">\r\n");
      out.write("            <li><a href=\"../User/alterarUser.jsp?nome=");
      out.print( nome );
      out.write("&id=");
      out.print( id );
      out.write("&email=");
      out.print( email );
      out.write("&senha=");
      out.print( senha );
      out.write("\">Alterar</a></li>\r\n");
      out.write("            <li><a href=\"../User/deletUser.jsp?id=");
      out.print(id);
      out.write("&senhaADM=");
      out.print( senhaADM );
      out.write("\">Deletar</a></li>\r\n");
      out.write("           </ul>\r\n");
      out.write("         </li>\r\n");
      out.write("      </ul>        \r\n");
      out.write("</nav>\r\n");
      out.write("</header>   \r\n");
      out.write("  <main>\r\n");
      out.write("                             <!-- Conteúdo principal do site -->\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("  <br>\r\n");
      out.write("   <h1 class=\"h1p\">Cirurgiões Veterinários para cães e gatos em Belém do Pará</h1>\r\n");
      out.write("    <img class=\"img-left \"src=\"Imagens/img1.jpg\">\r\n");
      out.write("   <p class=\"p1\">O centro cirúrgico da Clínica Santos possui os materiais e equipamentos necessários para realizar um procedimento seguro e com a mais alta qualidade, além de que contamos com uma médica veterinária especializada em cirurgia de tecidos moles.\r\n");
      out.write("   \r\n");
      out.write("    <br><br>\r\n");
      out.write("   As indicações de cirurgias são variadas, no entanto, as mais realizadas são as castrações seguidas da mastectomia e das cirurgias oculares e abdominais.</p>\r\n");
      out.write("  </div>   \r\n");
      out.write("   <div class=\"text2\">\r\n");
      out.write("     <h2>Serviços Veterinarios</h2>\r\n");
      out.write("     <div class=\"container2\">\r\n");
      out.write("      <div class=\"box\">\r\n");
      out.write("        <img class=\"icons\" src=\"Imagens/icon-Cirurgias.png\" alt=\"#\">\r\n");
      out.write("    <br><br>\r\n");
      out.write("    Cirurgias\r\n");
      out.write("    <br><br>\r\n");
      out.write("    Cirurgias de segurança com uma equipe especializada. Cirurgias veterinárias em Belém.\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"box\">\r\n");
      out.write("       <img class=\"icons\" src=\"Imagens/icon-fisio.png\" alt=\"#\">\r\n");
      out.write("    <br><br>\r\n");
      out.write("    Fisioterapia veterinária\r\n");
      out.write("    <br><br>\r\n");
      out.write("    Fisioterapia para animais de todos os portes. Fisioterapia animal em Belém.\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"box\">\r\n");
      out.write("      <img class=\"icons\" src=\"Imagens/icon-exame.png\" alt=\"#\">\r\n");
      out.write("    <br><br>\r\n");
      out.write("    Exames\r\n");
      out.write("    <br><br>\r\n");
      out.write("    Exames de sangue e exames laboratoriais. Exames médicos em Belém.\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"box\">\r\n");
      out.write("      <img class=\"icons\" src=\"Imagens/icon-consulta.png\" alt=\"#\">\r\n");
      out.write("    <br><br>\r\n");
      out.write("    Consultas\r\n");
      out.write("    <br><br>\r\n");
      out.write("    Agende sua consulta com um médico especializado. Consultas médicas em Belém.\r\n");
      out.write("      </div>\r\n");
      out.write("     <p class=\"p2\">Nossa clínica veterinária oferece serviços de qualidade com preços acessíveis. Consultas e exames em diversas especialidades. Conheça a nossa clínica em Belém.</p>\r\n");
      out.write("       <a href=\"#\" class=\"button2\">Sobre a clínica</a>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("    <br><br>\r\n");
      out.write("    <br><br>\r\n");
      out.write("    <br><br>\r\n");
      out.write("    <br><br>\r\n");
      out.write("   <div class=\"text3\">\r\n");
      out.write("   <h3>Castração De Animais</h3>\r\n");
      out.write("     <p class=\"p3\">Você sabia que a castração de animais é uma forma responsável de cuidar de nossos companheiros de quatro patas? Além de prevenir a reprodução indesejada, a castração traz inúmeros benefícios para a saúde e bem-estar dos animais. Consultas e exames em diversas especialidades. Conheça a nossa clínica em Belém.</p>\r\n");
      out.write("       <a href=\"#\" class=\"button3\">Saiba Mais</a>\r\n");
      out.write("   </div>\r\n");
      out.write("  </main>\r\n");
      out.write("  <footer class=\"footer\">\r\n");
      out.write(" <p>Todos os direitos reservados &copy; 2023 | Clínica Veterinária Santos</p>\r\n");
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
