/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-09-17 14:27:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Animal_005fUser;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import DAO.UserDAO;
import DTO.UserDTO;
import DAO.AnimalClienteDAO;
import DTO.Animal_UserDTO;
import java.util.ArrayList;

public final class Pagina_005fanimal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("DTO.UserDTO");
    _jspx_imports_classes.add("DAO.AnimalClienteDAO");
    _jspx_imports_classes.add("DAO.UserDAO");
    _jspx_imports_classes.add("DTO.Animal_UserDTO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0\" />\r\n");
      out.write("    <title>Tela de Listar Cliente</title>\r\n");
      out.write("     <link rel=\"stylesheet\" href=\"CSS.css\">\r\n");
      out.write("    <style>\r\n");
      out.write("    \r\n");
      out.write("      @charset \"ISO-8859-1\";\r\n");
      out.write("  /* Estilo Geral */\r\n");
      out.write("      * {\r\n");
      out.write("      margin: 0;\r\n");
      out.write("      padding: 0;\r\n");
      out.write("      box-sizing: border-box;\r\n");
      out.write("      }\r\n");
      out.write("      body {\r\n");
      out.write("      min-height: 100vh;\r\n");
      out.write("      min-width: 100vw;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      justify-content: center;\r\n");
      out.write("      background: linear-gradient(45deg, rgb(0, 0, 255), rgb(20, 20, 210), rgb(30, 30, 146), rgb(32, 32, 100));\r\n");
      out.write("      font-family: Arial, Helvetica, sans-serif;\r\n");
      out.write("      }\r\n");
      out.write("      main.container {\r\n");
      out.write("      background: white;\r\n");
      out.write("      padding: 2rem;\r\n");
      out.write("      box-shadow: 5px 5px 15px rgba(0, 0, 0, 0.2);\r\n");
      out.write("      border-radius: 8px;\r\n");
      out.write("      width: 90%;\r\n");
      out.write("      max-width: 1200px;\r\n");
      out.write("      }\r\n");
      out.write("      h1 {\r\n");
      out.write("      text-align: center;\r\n");
      out.write("     \r\n");
      out.write("      padding: 10px;\r\n");
      out.write("      }\r\n");
      out.write("      table {\r\n");
      out.write("      border-collapse: collapse;\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      }\r\n");
      out.write("      th, td {\r\n");
      out.write("      padding: 1rem;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      border-bottom: 1px solid #ccc;\r\n");
      out.write("      }\r\n");
      out.write("      th {\r\n");
      out.write("      background-color: lightgray;\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("      }\r\n");
      out.write("      #pesq-caixa{\r\n");
      out.write("      border: 1px solid #b7b6b6;\r\n");
      out.write("      border-radius: 4px;\r\n");
      out.write("      }\r\n");
      out.write("      #pesq-animal-button{\r\n");
      out.write("      background: linear-gradient(45deg, rgb(0, 0, 255), rgb(20, 20, 210), rgb(30, 30, 146), rgb(32, 32, 100));\r\n");
      out.write("      color: white;\r\n");
      out.write("      padding: 12px ;\r\n");
      out.write("      border: none;\r\n");
      out.write("      border-radius: 5px;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("      font-size: 16px\r\n");
      out.write("      }\r\n");
      out.write("      #desfazer-button{\r\n");
      out.write("      background: linear-gradient(45deg, rgb(255, 0, 0), rgb(210, 20, 20), rgb(146, 30, 30), rgb(100, 32, 32));\r\n");
      out.write("      color: white;\r\n");
      out.write("      padding: 12px ;\r\n");
      out.write("      border: none;\r\n");
      out.write("      border-radius: 5px;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("      font-size: 16px\r\n");
      out.write("      }\r\n");
      out.write("      .button-Dados{\r\n");
      out.write("      display: inline-block;\r\n");
      out.write("      margin-top: 1rem;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      background-color: #1E90FF;\r\n");
      out.write("      color: #fff;\r\n");
      out.write("      padding: 0.5rem 1rem;\r\n");
      out.write("      border-radius: 4px;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("      border: none;\r\n");
      out.write("      font-size: 15px;\r\n");
      out.write("      }\r\n");
      out.write("      #delet-button{\r\n");
      out.write("      display: inline-block;\r\n");
      out.write("      margin-top: 1rem;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      background-color: rgb(255, 0, 0);\r\n");
      out.write("      color: #fff;\r\n");
      out.write("      padding: 0.5rem 1rem;\r\n");
      out.write("      border-radius: 4px;\r\n");
      out.write("      }\r\n");
      out.write("      #alt-button{\r\n");
      out.write("      display: inline-block;\r\n");
      out.write("      margin-top: 1rem;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      background-color: rgb(153, 255, 0);\r\n");
      out.write("      color: #fff;\r\n");
      out.write("      padding: 0.5rem 1rem;\r\n");
      out.write("      border-radius: 4px;\r\n");
      out.write("      }\r\n");
      out.write("      #cadastrar-button {\r\n");
      out.write("      display: inline-block;\r\n");
      out.write("      margin-left: 0%;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      background-color: #333;\r\n");
      out.write("      color: #fff;\r\n");
      out.write("      padding: 10px;\r\n");
      out.write("      border-radius: 4px;\r\n");
      out.write("      margin-bottom:2px	;\r\n");
      out.write("      }\r\n");
      out.write("      .button_vacina {\r\n");
      out.write("      display: inline-block;\r\n");
      out.write("      margin-top: 1rem;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      background-color: #3087db;\r\n");
      out.write("      color: #fff;\r\n");
      out.write("      padding: 0.5rem 1rem;\r\n");
      out.write("      border-radius: 4px;\r\n");
      out.write("      border: none;\r\n");
      out.write("      font-size:16px;\r\n");
      out.write("      }\r\n");
      out.write("      .button_vacina:hover{\r\n");
      out.write("      transform: scale(0.95); \r\n");
      out.write("      transition: transform 0.3s ease;\r\n");
      out.write("      }\r\n");
      out.write("      #pesq-button:hover {\r\n");
      out.write("      transform: scale(0.95); \r\n");
      out.write("      transition: transform 0.3s ease; \r\n");
      out.write("      }\r\n");
      out.write("      #delet-button:hover {\r\n");
      out.write("      transform: scale(0.95); \r\n");
      out.write("      transition: transform 0.3s ease; \r\n");
      out.write("      }\r\n");
      out.write("      .button-Dados:hover {\r\n");
      out.write("      transform: scale(0.95); \r\n");
      out.write("      transition: transform 0.3s ease; \r\n");
      out.write("      }\r\n");
      out.write("      #alt-button:hover {\r\n");
      out.write("      transform: scale(0.95); \r\n");
      out.write("      transition: transform 0.3s ease;\r\n");
      out.write("      }\r\n");
      out.write("      #cadastrar-button:hover {\r\n");
      out.write("      transform: scale(0.95);\r\n");
      out.write("      transition: transform 0.3s ease;\r\n");
      out.write("      }\r\n");
      out.write("      /** modal do cadastrar **/\r\n");
      out.write("      /* Estilos do modal */\r\n");
      out.write("      .modal {\r\n");
      out.write("      display: none;\r\n");
      out.write("      position: fixed;\r\n");
      out.write("      z-index: 1;\r\n");
      out.write("      left: 0;\r\n");
      out.write("      top: 0;\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      height: 100%;\r\n");
      out.write("      overflow: auto;\r\n");
      out.write("      background-color: rgba(0, 0, 0, 0.6);\r\n");
      out.write("      }\r\n");
      out.write("      .modal-content {\r\n");
      out.write("      background-color: #fff;\r\n");
      out.write("      margin: 6% auto;\r\n");
      out.write("      padding: 20px;\r\n");
      out.write("      border-radius: 8px;\r\n");
      out.write("      box-shadow: 0px 0px 20px rgba(0, 0, 0, 0.3);\r\n");
      out.write("      max-width: 500px;\r\n");
      out.write("      width: 80%;\r\n");
      out.write("      }\r\n");
      out.write("      .close {\r\n");
      out.write("      color: #1e1d1d;\r\n");
      out.write("      float: right;\r\n");
      out.write("      font-size: 30px;\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("      }\r\n");
      out.write("      .close:hover {\r\n");
      out.write("      color: #525151;\r\n");
      out.write("      }\r\n");
      out.write("      .modal-form{\r\n");
      out.write("      display: flex;\r\n");
      out.write("      flex-direction: column;\r\n");
      out.write("      }\r\n");
      out.write("      input, .button-modal {\r\n");
      out.write("      margin-bottom: 5px;\r\n");
      out.write("      padding: 12px;\r\n");
      out.write("      border: 2px solid #868686;\r\n");
      out.write("      border-radius: 5px;\r\n");
      out.write("      outline: none;\r\n");
      out.write("      transition: border-color 0.3s;\r\n");
      out.write("      font-size: 16px;\r\n");
      out.write("      }\r\n");
      out.write("      input:hover {\r\n");
      out.write("      border-color: #1e8fffa5;\r\n");
      out.write("      }\r\n");
      out.write("      .button-modal {\r\n");
      out.write("      padding: 12px;\r\n");
      out.write("      background-color: #1E90FF;\r\n");
      out.write("      color: white;\r\n");
      out.write("      border: none;\r\n");
      out.write("      border-radius: 5px;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("      font-weight: 600;\r\n");
      out.write("      transition: background-color 0.3s;\r\n");
      out.write("      }\r\n");
      out.write("      .button-modal:hover {\r\n");
      out.write("      background-color: #75aade;\r\n");
      out.write("      }\r\n");
      out.write("      .container {\r\n");
      out.write("      padding: 10px;\r\n");
      out.write("      }  \r\n");
      out.write("      /* \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\zzzzz */\r\n");
      out.write("      .register {\r\n");
      out.write("      color: #1E90FF;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("      text-decoration: underline;\r\n");
      out.write("      }\r\n");
      out.write("      .cont{\r\n");
      out.write("      display: flex;\r\n");
      out.write("      justify-content: space-between ;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      justify-items: center;\r\n");
      out.write("      }\r\n");
      out.write("      select {\r\n");
      out.write("      margin-bottom: 5px;\r\n");
      out.write("      padding: 12px;\r\n");
      out.write("      border: 2px solid #868686;\r\n");
      out.write("      border-radius: 5px;\r\n");
      out.write("      outline: none;\r\n");
      out.write("      transition: border-color 0.3s;\r\n");
      out.write("      font-size: 16px;\r\n");
      out.write("      background-color: white; /* Cor de fundo */\r\n");
      out.write("      color: #333; /* Cor do texto */\r\n");
      out.write("      width: 100%; /* Preencha 100% da largura do elemento pai */\r\n");
      out.write("      }\r\n");
      out.write("      /* Estilo quando hover (mouse sobre o elemento) */\r\n");
      out.write("      select:hover {\r\n");
      out.write("      border-color: #1e8fffa5;\r\n");
      out.write("      }\r\n");
      out.write("      /* Estilize o placeholder no select */\r\n");
      out.write("      select {\r\n");
      out.write("      color: #000; /* Cor desejada para o placeholder */\r\n");
      out.write("      }\r\n");
      out.write("      /* Estilize o placeholder no input type date */\r\n");
      out.write("      input[type=\"date\"]::placeholder {\r\n");
      out.write("      color: #000; /* Cor desejada para o placeholder */\r\n");
      out.write("      }\r\n");
      out.write("      /* Estilize o placeholder no input type text */\r\n");
      out.write("      input[type=\"text\"]::placeholder {\r\n");
      out.write("      color: #000; /* Cor desejada para o placeholder */\r\n");
      out.write("      }\r\n");
      out.write("      .material-symbols-outlined{\r\n");
      out.write("      cursor:pointer;\r\n");
      out.write("      }\r\n");
      out.write("      .material-symbols-outlined:hover{\r\n");
      out.write("      background-color: #1E90FF;\r\n");
      out.write("      color: #ffffff;\r\n");
      out.write("      border-radius: 10px;\r\n");
      out.write("      }\r\n");
      out.write("      /*modal dados */\r\n");
      out.write("      #modal-dados-dados {\r\n");
      out.write("      background-color: #333;\r\n");
      out.write("      color: #fff;\r\n");
      out.write("      padding: 10px 20px;\r\n");
      out.write("      border: none;\r\n");
      out.write("      border-radius: 5px;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("      }\r\n");
      out.write("      #modal-dados-dados:hover {\r\n");
      out.write("      background-color: #555; /* Cor mais escura no hover */\r\n");
      out.write("      }\r\n");
      out.write("      /* Estilização do modal */\r\n");
      out.write("      .modal-dados {\r\n");
      out.write("      display: none;\r\n");
      out.write("      position: fixed;\r\n");
      out.write("      top: 0;\r\n");
      out.write("      left: 0;\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      height: 100%;\r\n");
      out.write("      background-color: rgba(0, 0, 0, 0.7); \r\n");
      out.write("      }\r\n");
      out.write("      .modal-container {\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      top: 50%;\r\n");
      out.write("      left: 50%;\r\n");
      out.write("      transform: translate(-50%, -50%);\r\n");
      out.write("      background-color: #fff;\r\n");
      out.write("      border-radius: 5px;\r\n");
      out.write("      box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);\r\n");
      out.write("      background: white;\r\n");
      out.write("      padding: 3rem;\r\n");
      out.write("      box-shadow: 5px 5px 15px rgba(0, 0, 0, 0.2);\r\n");
      out.write("      border-radius: 8px;\r\n");
      out.write("      width: 90%;\r\n");
      out.write("      max-width: 1200px;\r\n");
      out.write("      }\r\n");
      out.write("      .fechar {\r\n");
      out.write("      color: #1e1d1d;\r\n");
      out.write("      float: right;\r\n");
      out.write("      font-size: 30px;\r\n");
      out.write("      font-weight: bold;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("     \r\n");
      out.write("      \r\n");
      out.write("    </style>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    ");
 
      int idDesejado = Integer.parseInt(request.getParameter("id_User")); // O ID referente ao usuario para filtrar
      
      AnimalClienteDAO animal = new AnimalClienteDAO();
      ArrayList<Animal_UserDTO> users = animal.ListarAnimaisClientes();
      int id_animal= 0;
      String nome_animal = "";
      String especie = "";
      String raca = "";
      String data_nascimento = "";
      
      
      
      UserDAO listar = new UserDAO();
      ArrayList<UserDTO> lista = listar.ArrayListarUser();
      String nome_User = "";
      String email_User = "";
      String senha_User = "";
      
      boolean encontrou = false; // Flag para indicar se pelo menos um usuário foi encontrado
      
      //manda para o form voltar
      for (UserDTO user : lista) {
          if (user.getId_user()== idDesejado) {
           
            nome_User = user.getNome();
            email_User = user.getEmail();
            senha_User = user.getSenha();            
          }
        }
      
      
      out.write("\r\n");
      out.write("    <main class=\"container\">\r\n");
      out.write("      <span onclick=\"voltar()\" class=\"material-symbols-outlined\">home</span>\r\n");
      out.write("      <h1>Lista de animais</h1>\r\n");
      out.write("      <div class=\"cont\">\r\n");
      out.write("        <div id=\"pesq-div\">\r\n");
      out.write("          <input type=\"text\" id=\"pesq-animal-caixa\" placeholder=\"Digite o nome do animal\">\r\n");
      out.write("          <button id=\"pesq-animal-button\">Pesquisar por Animal</button>\r\n");
      out.write("          <button id=\"desfazer-button\">Desfazer</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"cont-2\">\r\n");
      out.write("          <a href=\"#\" id=\"cadastrar-button\" onclick=\"openModalCadastrar()\">Cadastrar</a>   \r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <table>\r\n");
      out.write("        <tr>\r\n");
      out.write("          <th>Código animal</th>\r\n");
      out.write("          <th>Nome</th>\r\n");
      out.write("          <th>Ficha</th>\r\n");
      out.write("          <th>Alterar</th>\r\n");
      out.write("          <th>Deletar</th>\r\n");
      out.write("        </tr>\r\n");
      out.write("        ");

          for (Animal_UserDTO user : users) {
            if (user.getCliente().getId_user() == idDesejado) { // Verifica se o ID corresponde ao desejado
              encontrou = true; // Define a flag como verdadeira
              
              id_animal = user.getId_animal();
              nome_animal = user.getNome_animal();
              especie = user.getEspecie();
              raca = user.getRaca();
              data_nascimento = user.getData_nascimento();
          
      out.write("\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td>");
      out.print( user.getId_animal());
      out.write("</td>\r\n");
      out.write("          <td>");
      out.print( user.getNome_animal() );
      out.write("</td>\r\n");
      out.write("          <td>\r\n");
      out.write("            <button class=\"button-Dados\" onclick=\"mostrarModal(");
      out.print( id_animal );
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print( nome_animal );
      out.write("', '");
      out.print( especie );
      out.write("', '");
      out.print( raca );
      out.write("', '");
      out.print( data_nascimento );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(nome_User);
      out.write("')\">Dados</button>\r\n");
      out.write("          </td>\r\n");
      out.write("          <td><a  href=\"#\" id=\"alt-button\" onclick=\"preencherFormularioAlterar(");
      out.print( id_animal );
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print( nome_animal );
      out.write("', '");
      out.print( especie );
      out.write("', '");
      out.print( raca );
      out.write("', '");
      out.print( data_nascimento );
      out.write("')\">Alterar</a></td>\r\n");
      out.write("          <td><a href=\"#\" id=\"delet-button\" onclick=\"preencherFormularioDeletar(");
      out.print( id_animal );
      out.write(',');
      out.write(' ');
      out.write('\'');
      out.print( nome_animal );
      out.write("', '");
      out.print( especie );
      out.write("', '");
      out.print( raca );
      out.write("', '");
      out.print( data_nascimento );
      out.write("')\">Deletar</a></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr id=\"animal-nao-encontrado\" style=\"display: none;\">\r\n");
      out.write("          <td colspan=\"6\">\r\n");
      out.write("            <h1>Animal não encontrado</h1>\r\n");
      out.write("          </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        ");

          }
          }
          
          if (!encontrou) {
          
      out.write("\r\n");
      out.write("        <table>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td colspan=\"1\">\r\n");
      out.write("              <h1>Você não possui animais cadastrados</h1>\r\n");
      out.write("            </td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          ");

            }
            
      out.write("\r\n");
      out.write("        </table>\r\n");
      out.write("      </table>\r\n");
      out.write("      <!-- modal cadastrar animal -->\r\n");
      out.write("      <div id=\"cadastrar\" class=\"modal\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("          <span class=\"close\" onclick=\"closeModal_cadastrar()\">&times;</span>\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <h1 class=\"cadastra\">Cadastre seu animal</h1>\r\n");
      out.write("          </div>\r\n");
      out.write("          <form action=\"Cadastrar_animal.jsp\" method=\"post\" class=\"modal-form\">\r\n");
      out.write("            <input type=\"text\" id=\"nome_animal\" name=\"nome_animal\" placeholder=\"Nome do animal\" required>\r\n");
      out.write("            <select id=\"especie\" name=\"especie\" required>\r\n");
      out.write("              <option value=\"\">Selecione uma espécie</option>\r\n");
      out.write("              <option value=\"Cachorro\">Cachorro</option>\r\n");
      out.write("              <option value=\"Gato\">Gato</option>\r\n");
      out.write("              <option value=\"Pássaro\">Pássaro</option>\r\n");
      out.write("              <option value=\"Hamster\">Hamster</option>\r\n");
      out.write("              <option value=\"Coelho\">Coelho</option>\r\n");
      out.write("              <option value=\"Rato\">Rato</option>\r\n");
      out.write("              <option value=\"Peixe\">Peixe</option>\r\n");
      out.write("              <option value=\"Cavalo\">Cavalo</option>\r\n");
      out.write("              <option value=\"Papagaio\">Papagaio</option>\r\n");
      out.write("              <option value=\"Tartaruga\">Tartaruga</option>\r\n");
      out.write("              <option value=\"Galinha\">Galinha</option>\r\n");
      out.write("              <option value=\"Porco\">Porco</option>\r\n");
      out.write("              <option value=\"Serpente\">Serpente</option>\r\n");
      out.write("              <option value=\"Elefante\">Elefante</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            <select id=\"raca\" name=\"raca\" placeholder=\"Raça animal\" required >\r\n");
      out.write("              <option value=\"\">Selecione uma raça</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            <input type=\"date\" id=\"data_nascimento\" name=\"data_nascimento\" required>\r\n");
      out.write("            <input type=\"hidden\" id=\"id_cliente\" name=\"id_cliente\" value=\"");
      out.print( idDesejado );
      out.write("\">\r\n");
      out.write("            <button type=\"submit\" class=\"button-modal\">Cadastrar</button>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- modal alterar animal -->\r\n");
      out.write("      <div id=\"alterar\" class=\"modal\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("          <span class=\"close\" onclick=\"closeModalAlterar()\">&times;</span>\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <h1>Alterar</h1>\r\n");
      out.write("          </div>\r\n");
      out.write("          <form action=\"Alterar_animal.jsp?idDesejado=");
      out.print(idDesejado);
      out.write("\" method=\"post\"  class=\"modal-form\">\r\n");
      out.write("            <p>Código animal:</p>\r\n");
      out.write("            <input type=\"text\" name=\"id_animal_altera\" id=\"id_animal_altera\" disabled=\"disabled\" value=\"\">\r\n");
      out.write("            <input type=\"hidden\" name=\"id_animal_hidden_altera\" id=\"id_animal_hidden_altera\" value=\"\">\r\n");
      out.write("            <p>Nome:</p>\r\n");
      out.write("            <input type=\"text\" name=\"nome_altera\" id=\"nome_altera\"  value=\"\">\r\n");
      out.write("            <p>Especie:</p>\r\n");
      out.write("            <select  name=\"especie_animal_altera\" id=\"especie_animal_altera\" onchange=\"carregarRacas()\" required>\r\n");
      out.write("              <option value=\"Cachorro\">Cachorro</option>\r\n");
      out.write("              <option value=\"Gato\">Gato</option>\r\n");
      out.write("              <option value=\"Pássaro\">Pássaro</option>\r\n");
      out.write("              <option value=\"Hamster\">Hamster</option>\r\n");
      out.write("              <option value=\"Coelho\">Coelho</option>\r\n");
      out.write("              <option value=\"Rato\">Rato</option>\r\n");
      out.write("              <option value=\"Peixe\">Peixe</option>\r\n");
      out.write("              <option value=\"Cavalo\">Cavalo</option>\r\n");
      out.write("              <option value=\"Papagaio\">Papagaio</option>\r\n");
      out.write("              <option value=\"Tartaruga\">Tartaruga</option>\r\n");
      out.write("              <option value=\"Galinha\">Galinha</option>\r\n");
      out.write("              <option value=\"Porco\">Porco</option>\r\n");
      out.write("              <option value=\"Serpente\">Serpente</option>\r\n");
      out.write("              <option value=\"Elefante\">Elefante</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            <p>Raça:</p>\r\n");
      out.write("            <select name=\"raca_animal_altera\" id=\"raca_animal_altera\">\r\n");
      out.write("            </select>\r\n");
      out.write("            <p>Data de nascimento:	</p>\r\n");
      out.write("            <input type=\"date\" name=\"data_nascimento_animal_altera\" id=\"data_nascimento_animal_altera\" Value=\"\" >\r\n");
      out.write("            <button type=\"submit\" class=\"button-modal\">Alterar</button>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- modal deletar animal-->\r\n");
      out.write("      <div id=\"deletar\" class=\"modal\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("          <span class=\"close\" onclick=\"closeModal_Deletar()\">&times;</span>\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <h1>Deletar</h1>\r\n");
      out.write("          </div>\r\n");
      out.write("          <form action=\"Deletar_animal.jsp?idDesejado=");
      out.print(idDesejado);
      out.write("\" method=\"post\"  class=\"modal-form\">\r\n");
      out.write("            <p>Código animal:</p>\r\n");
      out.write("            <input type=\"text\" name=\"id_animal\" id=\"id_animal\" disabled=\"disabled\" value=\"\">\r\n");
      out.write("            <input type=\"hidden\" name=\"id_animal_hidden\" id=\"id_animal_hidden\" value=\"\">\r\n");
      out.write("            <p>Nome:</p>\r\n");
      out.write("            <input type=\"text\" name=\"nome\" id=\"nome\" disabled=\"disabled\" value=\"\">\r\n");
      out.write("            <p>Especie:</p>\r\n");
      out.write("            <input type=\"text\" name=\"especie_animal\" id=\"especie_animal\" disabled=\"disabled\" Value=\"\" >\r\n");
      out.write("            <p>Raça:</p>\r\n");
      out.write("            <input type=\"text\" name=\"raca_animal\" id=\"raca_animal\" disabled=\"disabled\" value=\"\" >\r\n");
      out.write("            <p>Data de nascimento:	</p>\r\n");
      out.write("            <input type=\"date\" name=\"data_nascimento_animal\" id=\"data_nascimento_animal\" disabled=\"disabled\" Value=\"\" >\r\n");
      out.write("            <button type=\"submit\" class=\"button-modal\">Deletar</button>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!--modal dados  -->\r\n");
      out.write("      <div id=\"myModal\" class=\"modal-dados\">\r\n");
      out.write("        <div class=\"modal-container\">\r\n");
      out.write("          <div></div>\r\n");
      out.write("          <span class=\"close\" onclick=\"fecharModal()\">&times;</span>\r\n");
      out.write("          <h1>Dadoso do animal</h1>\r\n");
      out.write("          <table border=\"1\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <th>Dono</th>\r\n");
      out.write("              <th>Nome animal</th>\r\n");
      out.write("              <th>Especie</th>\r\n");
      out.write("              <th>Raça</th>\r\n");
      out.write("              <th>Data de nascimento</th>\r\n");
      out.write("              <th>id do animal</th>\r\n");
      out.write("              <th>Carteira de vacinas </th>\r\n");
      out.write("            </tr>\r\n");
      out.write("            ");
 
              
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td id=\"nome_dono\"> </td>\r\n");
      out.write("              <td id=\"nome_dados\"></td>\r\n");
      out.write("              <td id=\"especie_animal_dados\"></td>\r\n");
      out.write("              <td id=\"raca_animal_dados\"></td>\r\n");
      out.write("              <td id=\"data_nascimento_animal_dados\"></td>\r\n");
      out.write("              <td id=\"id_animal_dados\"></td>\r\n");
      out.write("              <td ><button class=\"button_vacina\">Vacinas</button></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            ");
 
              
      out.write("\r\n");
      out.write("          </table>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      ");
       
        
      out.write("\r\n");
      out.write("      <!-- form para voltar para Tela_de_Logado --> \r\n");
      out.write("      <form id=\"return_Form\" action=\"../index/Logado/Tela_de_Logado.jsp\" method=\"post\">\r\n");
      out.write("        <input type=\"hidden\" name=\"nome_User\" id=\"nome_User\" value=\"");
      out.print(nome_User);
      out.write("\" />\r\n");
      out.write("        <input type=\"hidden\" name=\"email_User\" id=\"email_User\" value=\"");
      out.print(email_User);
      out.write("\" />\r\n");
      out.write("        <input type=\"hidden\" name=\"senha_User\" id=\"senha_User\" value=\"");
      out.print(senha_User);
      out.write("\" />\r\n");
      out.write("        <input type=\"hidden\" name=\"id_User\" id=\"id_User\" value=\"");
      out.print(idDesejado);
      out.write("\" />    \r\n");
      out.write("      </form>\r\n");
      out.write("    </main>\r\n");
      out.write("  </body>\r\n");
      out.write("  <script>\r\n");
      out.write("    function mostrarModal(id_animal, nome_animal, especie, raca, data_nascimento, nome_User) {\r\n");
      out.write("       document.getElementById(\"nome_dono\").textContent = nome_User;\r\n");
      out.write("    \r\n");
      out.write("       document.getElementById(\"nome_dados\").textContent = nome_animal;\r\n");
      out.write("       document.getElementById(\"especie_animal_dados\").textContent = especie;\r\n");
      out.write("       document.getElementById(\"raca_animal_dados\").textContent = raca;\r\n");
      out.write("    \r\n");
      out.write("      \r\n");
      out.write("       const dataNascimentoFormatada = new Date(data_nascimento).toLocaleDateString('pt-BR');\r\n");
      out.write("    \r\n");
      out.write("       document.getElementById(\"data_nascimento_animal_dados\").textContent = dataNascimentoFormatada;\r\n");
      out.write("    \r\n");
      out.write("       document.getElementById(\"id_animal_dados\").textContent = id_animal;\r\n");
      out.write("    \r\n");
      out.write("       document.getElementById(\"myModal\").style.display = \"block\";\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    document.addEventListener(\"DOMContentLoaded\", function () {\r\n");
      out.write("     const inputPesquisaAnimal = document.getElementById(\"pesq-animal-caixa\");\r\n");
      out.write("     const pesquisarAnimalButton = document.getElementById(\"pesq-animal-button\");\r\n");
      out.write("     const tabela = document.querySelector(\"table\");\r\n");
      out.write("     const linhas = tabela.getElementsByTagName(\"tr\");\r\n");
      out.write("     const animalNaoEncontradoRow = document.getElementById(\"animal-nao-encontrado\");\r\n");
      out.write("    \r\n");
      out.write("     // Crie uma cópia do estado inicial da tabela\r\n");
      out.write("     const estadoInicialTabela = [...linhas].map((linha) => linha.style.display);\r\n");
      out.write("    \r\n");
      out.write("     pesquisarAnimalButton.addEventListener(\"click\", function () {\r\n");
      out.write("       const termoPesquisaAnimal = inputPesquisaAnimal.value.toLowerCase();\r\n");
      out.write("       let animalEncontrado = false;\r\n");
      out.write("    \r\n");
      out.write("       for (let i = 1; i < linhas.length; i++) {\r\n");
      out.write("         const animalNomeCelula = linhas[i].getElementsByTagName(\"td\")[1];\r\n");
      out.write("         if (animalNomeCelula) {\r\n");
      out.write("           const animalNomeTexto = animalNomeCelula.textContent.toLowerCase();\r\n");
      out.write("           if (animalNomeTexto.includes(termoPesquisaAnimal)) {\r\n");
      out.write("             linhas[i].style.display = \"\";\r\n");
      out.write("             animalEncontrado = true;\r\n");
      out.write("           } else {\r\n");
      out.write("             linhas[i].style.display = \"none\";\r\n");
      out.write("           }\r\n");
      out.write("         }\r\n");
      out.write("       }\r\n");
      out.write("    \r\n");
      out.write("       // Mostra a linha \"Animal não encontrado\" se nenhum animal for encontrado\r\n");
      out.write("       animalNaoEncontradoRow.style.display = animalEncontrado ? \"none\" : \"\";\r\n");
      out.write("    \r\n");
      out.write("     });\r\n");
      out.write("    \r\n");
      out.write("     // Adicione um evento de desfazer ao botão de desfazer\r\n");
      out.write("     const desfazerButton = document.getElementById(\"desfazer-button\");\r\n");
      out.write("     desfazerButton.addEventListener(\"click\", function () {\r\n");
      out.write("       // Restaure o estado inicial da tabela\r\n");
      out.write("       for (let i = 1; i < linhas.length; i++) {\r\n");
      out.write("         linhas[i].style.display = estadoInicialTabela[i];\r\n");
      out.write("       }\r\n");
      out.write("       animalNaoEncontradoRow.style.display = \"none\";\r\n");
      out.write("     });\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    // modal cadastrar \r\n");
      out.write("      function openModalCadastrar() {\r\n");
      out.write("      	document.getElementById(\"cadastrar\").style.display = \"block\";\r\n");
      out.write("      	}\r\n");
      out.write("      function closeModal_cadastrar() {\r\n");
      out.write("      	document.getElementById(\"cadastrar\").style.display = \"none\";\r\n");
      out.write("      	}\r\n");
      out.write("      \r\n");
      out.write("    //modal deletar\r\n");
      out.write("      function closeModal_Deletar() {\r\n");
      out.write("      	document.getElementById(\"deletar\").style.display = \"none\";\r\n");
      out.write("      	}\r\n");
      out.write("      	\r\n");
      out.write("    //modal alterar\r\n");
      out.write("      function closeModalAlterar() {\r\n");
      out.write("      	document.getElementById(\"alterar\").style.display = \"none\";\r\n");
      out.write("      	}\r\n");
      out.write("      \r\n");
      out.write("    //modal dados\r\n");
      out.write("      \r\n");
      out.write("      function fecharModal() {\r\n");
      out.write("      	document.getElementById(\"myModal\").style.display = \"none\";\r\n");
      out.write("      	}\r\n");
      out.write("    //não lembro para que serve, porém serve para voltar para uma determinada página\r\n");
      out.write("      function voltar() {\r\n");
      out.write("          document.getElementById(\"return_Form\").submit();\r\n");
      out.write("          }\r\n");
      out.write("      \r\n");
      out.write("    //Preencher os campos do formulário de alterção com os valores recebidospara alterar\r\n");
      out.write("        function preencherFormularioAlterar(id_animal, nome_animal, especie, raca, data_nascimento) {\r\n");
      out.write("         \r\n");
      out.write("         document.getElementById(\"id_animal_altera\").value = id_animal;\r\n");
      out.write("         document.getElementById(\"nome_altera\").value = nome_animal;\r\n");
      out.write("         document.getElementById(\"especie_animal_altera\").value = especie;\r\n");
      out.write("         document.getElementById(\"raca_animal_altera\").value = raca;\r\n");
      out.write("         document.getElementById(\"data_nascimento_animal_altera\").value = data_nascimento;\r\n");
      out.write("         \r\n");
      out.write("         document.getElementById(\"id_animal_hidden_altera\").value = id_animal;\r\n");
      out.write("      \r\n");
      out.write("         document.getElementById(\"alterar\").style.display = \"block\";\r\n");
      out.write("         \r\n");
      out.write("         carregarRacas(raca);\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("    //Preencher os campos do formulário de deletar com os valores recebidos para deletar \r\n");
      out.write("        function preencherFormularioDeletar(id_animal, nome_animal, especie, raca, data_nascimento) {\r\n");
      out.write("      	    document.getElementById(\"id_animal\").value = id_animal;\r\n");
      out.write("      	    document.getElementById(\"nome\").value = nome_animal;\r\n");
      out.write("      	    document.getElementById(\"especie_animal\").value = especie;\r\n");
      out.write("      	    document.getElementById(\"raca_animal\").value = raca;\r\n");
      out.write("      	    document.getElementById(\"data_nascimento_animal\").value = data_nascimento;\r\n");
      out.write("      	    \r\n");
      out.write("      	    document.getElementById(\"id_animal_hidden\").value = id_animal;\r\n");
      out.write("      \r\n");
      out.write("      	    document.getElementById(\"deletar\").style.display = \"block\";\r\n");
      out.write("      	}\r\n");
      out.write("    \r\n");
      out.write("    //valores do select de alteração\r\n");
      out.write("        function carregarRacas(valor) {\r\n");
      out.write("      	  const especieSelectAltera = document.getElementById(\"especie_animal_altera\");\r\n");
      out.write("      	  const racaSelectAltera = document.getElementById(\"raca_animal_altera\");\r\n");
      out.write("      	  const exibe = valor;\r\n");
      out.write("      	\r\n");
      out.write("      	  const racasPossiveisAltera = {\r\n");
      out.write("      			  \"Cachorro\": [\"Vira lata \",\"Pastor Alemão\", \"Golden Retriever\", \"Labrador\", \"Bulldog\", \"Poodle\", \"Boxer\", \"Husky\", \"Dálmata\", \"Bulldog Francês\", \"Chihuahua\"],\r\n");
      out.write("      		        \"Gato\": [\"Siamese\", \"Persa\", \"Bengal\", \"Maine Coon\", \"Sphynx\", \"Ragdoll\", \"British Shorthair\", \"Scottish Fold\", \"Siberian\", \"Devon Rex\"],\r\n");
      out.write("      		        \"Pássaro\": [\"Cacatua\", \"Canário\", \"Periquito\", \"Calopsita\", \"Papagaio\", \"Agapornis\", \"Arara\", \"Tucano\", \"Pardal\", \"Ave-do-paraíso\"],\r\n");
      out.write("      		        \"Hamster\": [\"Sírio\", \"Russo\", \"Roborovski\", \"Chinês\", \"Campbell\", \"Angorá\", \"Manchuriano\", \"Mongol\", \"Siberiano\", \"Djungarian\"],\r\n");
      out.write("      		        \"Coelho\": [\"Holland Lop\", \"Mini Rex\", \"Holandês\", \"Lebre Belga\", \"Fuzzy Lop\", \"Mini Lionhead\", \"Angorá\", \"Chinchila\", \"Mini Satin\", \"Californiano\"],\r\n");
      out.write("      		        \"Rato\": [\"Rato de Estimação\", \"Rato Selvagem\", \"Rato de Laboratório\", \"Rato Dumbo\", \"Rato Siamese\", \"Rato Hooded\", \"Rato Albino\", \"Rato de Cauda Longa\", \"Rato Fawn\", \"Rato de Cauda Curta\"],\r\n");
      out.write("      		        \"Peixe\": [\"Betta\", \"Guppy\", \"Tetra Neón\", \"Platy\", \"Peixe-espada\", \"Danio Zebra\", \"Peixe-palhaço\", \"Corydora\", \"Bala Shark\", \"Molinésia\"],\r\n");
      out.write("      		        \"Cavalo\": [\"Cavalo Árabe\", \"Puro-Sangue Inglês\", \"Quarto de Milha\", \"Cavalo Appaloosa\", \"Cavalo Pônei\", \"Cavalo Shire\", \"Cavalo Frísio\", \"Cavalo Tennessee Walker\", \"Cavalo Andaluz\", \"Cavalo Haflinger\"],\r\n");
      out.write("      		        \"Papagaio\": [\"Papagaio-do-congo\", \"Papagaio-cinzento\", \"Papagaio-de-cabeça-amarela\", \"Papagaio-de-cabeça-vermelha\", \"Papagaio-amazônico\", \"Papagaio-eclectus\", \"Papagaio-rosa\", \"Papagaio-molucano\", \"Papagaio-de-crista\", \"Papagaio-araçari\"],\r\n");
      out.write("      		        \"Tartaruga\": [\"Tartaruga-de-ouro\", \"Tartaruga-de-ouvido-vermelho\", \"Tartaruga-pintada\", \"Tartaruga-sulcata\", \"Tartaruga-leopardo\", \"Tartaruga-mordedora-comum\", \"Tartaruga-aligátor\", \"Tartaruga-mapa\", \"Tartaruga-de-caixa\", \"Tartaruga-africana-de-carapaça-macia\"],\r\n");
      out.write("      		        \"Galinha\": [\"Galinha-doméstica\", \"Galinha-seda\", \"Galinha-sussex\", \"Galinha-plymouth-rock\", \"Galinha-americana\", \"Galinha-araucana\", \"Galinha-brahma\", \"Galinha-orpington\", \"Galinha-wyandotte\", \"Galinha-leghorn\"],\r\n");
      out.write("      		        \"Porco\": [\"Porco-doméstico\", \"Porco-da-índia\", \"Porco-de-miniporco\", \"Porco-da-índia\", \"Porco-da-índia-skinny\", \"Porco-do-vietnã\", \"Porco-holandês\", \"Porco-kunekune\", \"Porco-mangalica\", \"Porco-peludo\"],\r\n");
      out.write("      		        \"Serpente\": [\"Serpente-de-milho\", \"Serpente-rei-da-califórnia\", \"Serpente-das-árvores\", \"Serpente-de-leite\", \"Serpente-de-milho\", \"Serpente-de-ratão\", \"Serpente-das-nuvens\", \"Serpente-boieira\", \"Serpente-rato-do-deserto\", \"Serpente-king-cobra\"],\r\n");
      out.write("      		        \"Elefante\": [\"Elefante-africano\", \"Elefante-asiático\", \"Elefante-da-floresta\", \"Elefante-da-savana\", \"Elefante-africano-das-florestas\", \"Elefante-indiano\", \"Elefante-africano-de-savanas\", \"Elefante-da-floresta-africana\", \"Elefante-pigmeu\", \"Elefante-do-sri-lanka\"]\r\n");
      out.write("      	  };\r\n");
      out.write("      	  \r\n");
      out.write("      	  const especieSelecionadaAltera = especieSelectAltera.value;\r\n");
      out.write("      	  const racasAltera = racasPossiveisAltera[especieSelecionadaAltera] || [];\r\n");
      out.write("      	  \r\n");
      out.write("      	  racaSelectAltera.innerHTML = \"\";  \r\n");
      out.write("      	  \r\n");
      out.write("      	  const optionPadrao = document.createElement(\"option\");\r\n");
      out.write("      	  optionPadrao.value = valor;\r\n");
      out.write("      	  if(valor !=null){\r\n");
      out.write("      		  optionPadrao.textContent = valor;\r\n");
      out.write("      		  \r\n");
      out.write("      	  }\r\n");
      out.write("      	  else{\r\n");
      out.write("      		  optionPadrao.textContent = \"Escolha\";\r\n");
      out.write("      	  }\r\n");
      out.write("      	  \r\n");
      out.write("      	  racaSelectAltera.appendChild(optionPadrao);\r\n");
      out.write("      	  \r\n");
      out.write("      	  racasAltera.forEach((raca) => {\r\n");
      out.write("      	    const option = document.createElement(\"option\");\r\n");
      out.write("      	    option.value = raca;\r\n");
      out.write("      	    option.textContent = raca;\r\n");
      out.write("      	    racaSelectAltera.appendChild(option);\r\n");
      out.write("      	  });\r\n");
      out.write("      	}\r\n");
      out.write("      \r\n");
      out.write("        \r\n");
      out.write("      \r\n");
      out.write("    //valores do select de cadastro\r\n");
      out.write("        const especieSelect = document.getElementById(\"especie\");\r\n");
      out.write("        const racaSelect = document.getElementById(\"raca\");\r\n");
      out.write("        \r\n");
      out.write("        const racasPossiveis = {\r\n");
      out.write("          \"Cachorro\": [\"Escolha\",\"Vira lata \",\"Pastor Alemão\", \"Golden Retriever\", \"Labrador\", \"Bulldog\", \"Poodle\", \"Boxer\", \"Husky\", \"Dálmata\", \"Bulldog Francês\", \"Chihuahua\"],\r\n");
      out.write("          \"Gato\": [\"Escolha\",\"Siamese\", \"Persa\", \"Bengal\", \"Maine Coon\", \"Sphynx\", \"Ragdoll\", \"British Shorthair\", \"Scottish Fold\", \"Siberian\", \"Devon Rex\"],\r\n");
      out.write("          \"Pássaro\": [\"Escolha\",\"Cacatua\", \"Canário\", \"Periquito\", \"Calopsita\", \"Papagaio\", \"Agapornis\", \"Arara\", \"Tucano\", \"Pardal\", \"Ave-do-paraíso\"],\r\n");
      out.write("          \"Hamster\": [\"Escolha\",\"Sírio\", \"Russo\", \"Roborovski\", \"Chinês\", \"Campbell\", \"Angorá\", \"Manchuriano\", \"Mongol\", \"Siberiano\", \"Djungarian\"],\r\n");
      out.write("          \"Coelho\": [\"Escolha\",\"Holland Lop\", \"Mini Rex\", \"Holandês\", \"Lebre Belga\", \"Fuzzy Lop\", \"Mini Lionhead\", \"Angorá\", \"Chinchila\", \"Mini Satin\", \"Californiano\"],\r\n");
      out.write("          \"Rato\": [\"Escolha\",\"Rato de Estimação\", \"Rato Selvagem\", \"Rato de Laboratório\", \"Rato Dumbo\", \"Rato Siamese\", \"Rato Hooded\", \"Rato Albino\", \"Rato de Cauda Longa\", \"Rato Fawn\", \"Rato de Cauda Curta\"],\r\n");
      out.write("          \"Peixe\": [\"Escolha\",\"Betta\", \"Guppy\", \"Tetra Neón\", \"Platy\", \"Peixe-espada\", \"Danio Zebra\", \"Peixe-palhaço\", \"Corydora\", \"Bala Shark\", \"Molinésia\"],\r\n");
      out.write("          \"Cavalo\": [\"Escolha\",\"Cavalo Árabe\", \"Puro-Sangue Inglês\", \"Quarto de Milha\", \"Cavalo Appaloosa\", \"Cavalo Pônei\", \"Cavalo Shire\", \"Cavalo Frísio\", \"Cavalo Tennessee Walker\", \"Cavalo Andaluz\", \"Cavalo Haflinger\"],\r\n");
      out.write("          \"Papagaio\": [\"Escolha\",\"Papagaio-do-congo\", \"Papagaio-cinzento\", \"Papagaio-de-cabeça-amarela\", \"Papagaio-de-cabeça-vermelha\", \"Papagaio-amazônico\", \"Papagaio-eclectus\", \"Papagaio-rosa\", \"Papagaio-molucano\", \"Papagaio-de-crista\", \"Papagaio-araçari\"],\r\n");
      out.write("          \"Tartaruga\": [\"Escolha\",\"Tartaruga-de-ouro\", \"Tartaruga-de-ouvido-vermelho\", \"Tartaruga-pintada\", \"Tartaruga-sulcata\", \"Tartaruga-leopardo\", \"Tartaruga-mordedora-comum\", \"Tartaruga-aligátor\", \"Tartaruga-mapa\", \"Tartaruga-de-caixa\", \"Tartaruga-africana-de-carapaça-macia\"],\r\n");
      out.write("          \"Galinha\": [\"Escolha\",\"Galinha-doméstica\", \"Galinha-seda\", \"Galinha-sussex\", \"Galinha-plymouth-rock\", \"Galinha-americana\", \"Galinha-araucana\", \"Galinha-brahma\", \"Galinha-orpington\", \"Galinha-wyandotte\", \"Galinha-leghorn\"],\r\n");
      out.write("          \"Porco\": [\"Escolha\",\"Porco-doméstico\", \"Porco-da-índia\", \"Porco-de-miniporco\", \"Porco-da-índia\", \"Porco-da-índia-skinny\", \"Porco-do-vietnã\", \"Porco-holandês\", \"Porco-kunekune\", \"Porco-mangalica\", \"Porco-peludo\"],\r\n");
      out.write("          \"Serpente\": [\"Escolha\",\"Serpente-de-milho\", \"Serpente-rei-da-califórnia\", \"Serpente-das-árvores\", \"Serpente-de-leite\", \"Serpente-de-milho\", \"Serpente-de-ratão\", \"Serpente-das-nuvens\", \"Serpente-boieira\", \"Serpente-rato-do-deserto\", \"Serpente-king-cobra\"],\r\n");
      out.write("          \"Elefante\": [\"Escolha\",\"Elefante-africano\", \"Elefante-asiático\", \"Elefante-da-floresta\", \"Elefante-da-savana\", \"Elefante-africano-das-florestas\", \"Elefante-indiano\", \"Elefante-africano-de-savanas\", \"Elefante-da-floresta-africana\", \"Elefante-pigmeu\", \"Elefante-do-sri-lanka\"]\r\n");
      out.write("        };\r\n");
      out.write("        \r\n");
      out.write("        especieSelect.addEventListener(\"change\", () => {\r\n");
      out.write("          const especieSelecionada = especieSelect.value;\r\n");
      out.write("          const racas = racasPossiveis[especieSelecionada] || [];\r\n");
      out.write("      \r\n");
      out.write("          if (racas.length > 0) {\r\n");
      out.write("            racaSelect.style.display = \"block\"; \r\n");
      out.write("          } else {\r\n");
      out.write("            racaSelect.style.display = \"none\"; \r\n");
      out.write("          }\r\n");
      out.write("          racaSelect.innerHTML = \"\";\r\n");
      out.write("          racas.forEach((raca) => {\r\n");
      out.write("            const option = document.createElement(\"option\");\r\n");
      out.write("            option.value = raca;\r\n");
      out.write("            option.textContent = raca;\r\n");
      out.write("            racaSelect.appendChild(option);\r\n");
      out.write("          });\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("    //retorno das págias ligadas a Pagina_animal\r\n");
      out.write("      var retorna = new URLSearchParams(window.location.search);\r\n");
      out.write("      var elemento = retorna.get('conf');\r\n");
      out.write("      \r\n");
      out.write("      switch (elemento) {\r\n");
      out.write("      case 'deleta':\r\n");
      out.write("      setTimeout(function() {\r\n");
      out.write("      alert('Animal deletado!');\r\n");
      out.write("      }, 100);\r\n");
      out.write("      break;\r\n");
      out.write("      \r\n");
      out.write("      case 'erro_deleta':\r\n");
      out.write("      setTimeout(function() {\r\n");
      out.write("      alert('O animal não pode ser deletado por algum motivo por parte do servidor!');\r\n");
      out.write("      }, 100);\r\n");
      out.write("      break;\r\n");
      out.write("      \r\n");
      out.write("      case 'erro_cadastra_animal':\r\n");
      out.write("      setTimeout(function() {\r\n");
      out.write("      alert('O animal não pode ser cadastrado por algum motivo por parte do servidor!');\r\n");
      out.write("      }, 100);\r\n");
      out.write("      break;\r\n");
      out.write("      }\r\n");
      out.write("  </script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
